import { NextRequest, NextResponse } from 'next/server'
import ExcelJS from 'exceljs'
import { requireFeeAccess } from '@/lib/auth'
import { buildFeeAuditReport, type BulkReport, type StudentReport, type Meta } from '@/lib/feeAuditReport'

// GET /api/fees/audit-report/excel?school_id=X&academic_year=Y[&grade&section][&student_id]
// Streams a multi-sheet .xlsx audit report.
export async function GET(req: NextRequest) {
  try {
    const p = req.nextUrl.searchParams
    const school_id     = p.get('school_id')
    const academic_year = p.get('academic_year')
    if (!school_id || !academic_year) return NextResponse.json({ error: 'school_id and academic_year required' }, { status: 400 })
    const access = await requireFeeAccess(school_id)
    if (!access) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

    const report = await buildFeeAuditReport({
      school_id, academic_year, grade: p.get('grade'), section: p.get('section'),
      student_id: p.get('student_id'), actor: access.actor,
    })

    const wb = new ExcelJS.Workbook()
    wb.creator = 'WLYL'
    wb.created = new Date()

    const fmtMoney = '#,##0.00'
    const headerFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } }
    const headerFont: Partial<ExcelJS.Font> = { color: { argb: 'FFFFFFFF' }, bold: true }

    function metaBlock(ws: ExcelJS.Worksheet, meta: Meta, title: string) {
      ws.addRow([title]).font = { size: 14, bold: true }
      ws.addRow([`School: ${meta.school_name}`])
      ws.addRow([`Academic Year: ${meta.academic_year}`])
      if (meta.scope) ws.addRow([`Scope: ${meta.scope}`])
      ws.addRow([`Generated By: ${meta.generated_by}`])
      ws.addRow([`Generated On: ${new Date(meta.generated_on).toLocaleString('en-IN')}`])
      ws.addRow([])
    }
    function headerRow(ws: ExcelJS.Worksheet, labels: string[]) {
      const r = ws.addRow(labels)
      r.eachCell(c => { c.fill = headerFill; c.font = headerFont; c.alignment = { horizontal: 'center' } })
      return r
    }
    function moneyCols(ws: ExcelJS.Worksheet, fromCol: number, toCol: number, rowNum: number) {
      for (let c = fromCol; c <= toCol; c++) ws.getCell(rowNum, c).numFmt = fmtMoney
    }

    if (report.kind === 'bulk') {
      const rep = report as BulkReport

      // Sheet 1 — Fee Summary
      const s1 = wb.addWorksheet('Summary')
      s1.columns = [{ width: 26 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }]
      metaBlock(s1, rep.meta, 'FEE AUDIT REPORT — SUMMARY')
      headerRow(s1, ['', 'Billed', 'Waived', 'Net Demand', 'Paid', 'Balance'])
      const sr = s1.addRow(['Total Fee', rep.summary.billed, rep.summary.waived, rep.summary.net_demand, rep.summary.paid, rep.summary.balance])
      moneyCols(s1, 2, 6, sr.number)
      s1.addRow([])
      s1.addRow([`Students: ${rep.summary.students}`])

      // Sheet 2 — Fee Type Summary
      const s2 = wb.addWorksheet('By Fee Type')
      s2.columns = [{ width: 24 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }]
      metaBlock(s2, rep.meta, 'FEE TYPE SUMMARY')
      headerRow(s2, ['Fee Type', 'Billed', 'Waived', 'Net Demand', 'Paid', 'Balance'])
      for (const t of rep.by_type) {
        const r = s2.addRow([t.fee_type, t.billed, t.waived, t.net_demand, t.paid, t.balance])
        moneyCols(s2, 2, 6, r.number)
      }

      // Sheet 3 — Change Log
      const s3 = wb.addWorksheet('Change Log')
      s3.columns = [{ width: 20 }, { width: 22 }, { width: 60 }, { width: 16 }, { width: 22 }]
      metaBlock(s3, rep.meta, 'FEE CHANGE LOG')
      headerRow(s3, ['Date & Time', 'Action', 'Detail', 'Amount', 'User'])
      for (const l of rep.change_log) {
        const r = s3.addRow([new Date(l.at).toLocaleString('en-IN'), l.type, l.detail, l.amount ?? '', l.user || ''])
        if (l.amount != null) s3.getCell(r.number, 4).numFmt = fmtMoney
      }

      // Sheet 4 — Class-wise
      const s4 = wb.addWorksheet('Class-wise')
      s4.columns = [{ width: 12 }, { width: 22 }, { width: 16 }, { width: 14 }, { width: 16 }, { width: 14 }, { width: 14 }]
      metaBlock(s4, rep.meta, 'CLASS-WISE FEE DETAILS')
      headerRow(s4, ['Class', 'Fee Type', 'Billed', 'Waived', 'Net Demand', 'Paid', 'Balance'])
      for (const c of rep.by_class) {
        const r = s4.addRow([c.class, c.fee_type, c.billed, c.waived, c.net_demand, c.paid, c.balance])
        moneyCols(s4, 3, 7, r.number)
      }

      // Sheet 5 — Student-wise (per fee type + subtotal per student)
      const s5 = wb.addWorksheet('Student-wise')
      s5.columns = [{ width: 26 }, { width: 14 }, { width: 12 }, { width: 22 }, { width: 16 }, { width: 18 }, { width: 14 }, { width: 14 }, { width: 16 }, { width: 14 }, { width: 14 }]
      metaBlock(s5, rep.meta, 'STUDENT-WISE FEE DETAILS (by fee type)')
      headerRow(s5, ['Student', 'Roll No', 'Class', 'Parent Name', 'Parent Phone', 'Fee Type', 'Billed', 'Waived', 'Net Demand', 'Paid', 'Balance'])
      for (const st of rep.by_student) {
        const label = st.is_subtotal ? 'SUBTOTAL' : st.fee_type
        const r = s5.addRow([st.student, st.roll_number, st.class, st.parent_name || '', st.parent_phone || '', label, st.billed, st.waived, st.net_demand, st.paid, st.balance])
        moneyCols(s5, 7, 11, r.number)
        if (st.is_subtotal) {
          r.eachCell(c => { c.font = { bold: true }; c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } } })
        }
      }

      const buf = await wb.xlsx.writeBuffer()
      const fname = `fee_audit_${rep.meta.scope?.replace(/\s+/g, '_') || 'school'}_${academic_year}.xlsx`
      return new NextResponse(buf, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="${fname}"`,
        },
      })
    }

    // ── INDIVIDUAL STUDENT ──
    const rep = report as StudentReport
    const ws = wb.addWorksheet('Student Fee Report')
    ws.columns = [{ width: 22 }, { width: 20 }, { width: 16 }, { width: 14 }, { width: 16 }, { width: 14 }, { width: 18 }]
    metaBlock(ws, rep.meta, 'INDIVIDUAL STUDENT FEE REPORT')
    // Profile
    ws.addRow(['Student', rep.student.name]); ws.addRow(['Roll No', rep.student.roll_number])
    ws.addRow(['Class', `${rep.student.grade}${rep.student.section || ''}`])
    ws.addRow(['Parent', rep.student.parent_name || '—']); ws.addRow(['Phone', rep.student.parent_phone || '—'])
    ws.addRow([])
    // Balance summary
    headerRow(ws, ['', 'Billed', 'Waived', 'Net Demand', 'Paid', 'Balance'])
    const br = ws.addRow(['Total', rep.balance.billed, rep.balance.waived, rep.balance.net_demand, rep.balance.paid, rep.balance.balance])
    moneyCols(ws, 2, 6, br.number)
    ws.addRow([])
    // Fee structure / bills
    ws.addRow(['FEE STRUCTURE']).font = { bold: true }
    headerRow(ws, ['Fee Type', 'Period', 'Billed', 'Waived', 'Paid', 'Balance', 'Status'])
    for (const b of rep.bills) {
      const r = ws.addRow([b.fee_type, b.period_label, b.billed, b.waived, b.paid, b.balance, b.status])
      moneyCols(ws, 3, 6, r.number)
    }
    ws.addRow([])
    // Payment history
    ws.addRow(['PAYMENT HISTORY']).font = { bold: true }
    headerRow(ws, ['Receipt', 'Date', 'Fee Type · Period', 'Amount', 'Mode', 'Status', 'Collected By'])
    for (const pmt of rep.payments) {
      const r = ws.addRow([pmt.receipt_number, pmt.paid_date, `${pmt.fee_type} · ${pmt.period_label}`, pmt.amount, pmt.payment_mode, pmt.payment_status, pmt.collected_by_name || ''])
      ws.getCell(r.number, 4).numFmt = fmtMoney
    }
    ws.addRow([])
    // Waivers
    ws.addRow(['WAIVERS']).font = { bold: true }
    headerRow(ws, ['Fee Type · Period', 'Type', 'Amount', 'Reason', 'Granted By', 'Status'])
    for (const w of rep.waivers) {
      const r = ws.addRow([`${w.fee_type} · ${w.period_label}`, w.waiver_type, w.waiver_amount, w.reason, w.granted_by_name || '', w.is_revoked ? 'Revoked' : 'Active'])
      ws.getCell(r.number, 3).numFmt = fmtMoney
    }

    const buf = await wb.xlsx.writeBuffer()
    const fname = `fee_report_${rep.student.name.replace(/\s+/g, '_')}_${academic_year}.xlsx`
    return new NextResponse(buf, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    })
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Failed'
    if (msg === 'Student not found') return NextResponse.json({ error: msg }, { status: 404 })
    console.error('[audit-report/excel]', err)
    return NextResponse.json({ error: 'Failed to build Excel report' }, { status: 500 })
  }
}
