export interface NewspaperTopic {
  title: string
  subtitle: string
  content: string
  fun_fact: string
  quiz_question: string
  quiz_answer: string
  quiz_options: string[]   // [correct, wrong1, wrong2, wrong3]
  topic: string
  category: string
}

// 64 pre-written topics — rotated by day-of-year (dayOfYear % NEWSPAPER_TOPICS.length)
export const NEWSPAPER_TOPICS: NewspaperTopic[] = [
  {
    title: 'The Internet of Things: Your Fridge Can Think!',
    subtitle: 'How everyday objects are getting smarter',
    content: 'The Internet of Things (IoT) refers to the network of physical devices embedded with sensors, software, and connectivity. From smart thermostats that learn your temperature preferences to fitness bands that monitor your heart rate, IoT is transforming how we interact with the world. There are currently over 15 billion connected devices globally, and this number is expected to reach 30 billion by 2030. IoT enables devices to collect and share data without human intervention, making our homes, cities, and industries more efficient. Smart cities use IoT sensors to manage traffic, reduce energy consumption, and improve public safety.',
    fun_fact: 'The first IoT device was a Coke machine at Carnegie Mellon University in the 1980s that could report its inventory over the internet!',
    quiz_question: 'What does IoT stand for?',
    quiz_answer: 'Internet of Things',
    quiz_options: ['Internet of Things', 'Internet of Technology', 'Integrated Output Tunnel', 'Internal Operating Terminal'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'Black Holes: Where Time Itself Bends',
    subtitle: 'The most mysterious objects in the universe',
    content: 'Black holes are regions of spacetime where gravity is so strong that nothing — not even light — can escape. They form when massive stars collapse at the end of their life cycles. The boundary around a black hole from which nothing can escape is called the "event horizon." Despite their name, black holes are not empty space — they contain enormous amounts of mass compressed into an incredibly small area. The supermassive black hole at the center of our Milky Way galaxy is called Sagittarius A* and has a mass about 4 million times that of our Sun. In 2019, scientists captured the first-ever image of a black hole using the Event Horizon Telescope.',
    fun_fact: 'If you fell into a black hole feet first, the gravity difference between your head and feet would stretch you like spaghetti — scientists call this "spaghettification"!',
    quiz_question: 'What is the boundary around a black hole called?',
    quiz_answer: 'Event horizon',
    quiz_options: ['Event horizon', 'Singularity point', 'Photon sphere', 'Gravitational lens'],
    topic: 'Space',
    category: 'Science & Tech',
  },
  {
    title: 'Photosynthesis: Plants Are Solar Panels!',
    subtitle: 'The chemical magic that feeds all life on Earth',
    content: 'Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight, water, and carbon dioxide into glucose and oxygen. This simple equation — 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂ — is the foundation of almost all life on Earth. Chlorophyll, the green pigment in plant leaves, absorbs red and blue light while reflecting green, which is why plants appear green. Photosynthesis removes about 2.5 billion tonnes of carbon dioxide from the atmosphere annually, making plants crucial in combating climate change. The Amazon rainforest alone produces 20% of the world\'s oxygen.',
    fun_fact: 'Plants lose about 90% of the water they absorb through tiny pores called stomata — a single large tree can release 400 litres of water into the air each day!',
    quiz_question: 'What green pigment in plants absorbs sunlight for photosynthesis?',
    quiz_answer: 'Chlorophyll',
    quiz_options: ['Chlorophyll', 'Carotene', 'Anthocyanin', 'Melanin'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'The Water Cycle: Earth\'s Natural Recycling System',
    subtitle: 'The same water dinosaurs drank is in your glass today',
    content: 'The water cycle, also called the hydrological cycle, is the continuous movement of water through Earth\'s systems. The four main stages are evaporation (water turning to vapor from oceans and lakes), condensation (vapor forming clouds), precipitation (water falling as rain or snow), and collection (water gathering in rivers, lakes, and groundwater). About 97% of Earth\'s water is in the oceans, 2% is frozen in glaciers, and less than 1% is fresh water available for use. The total amount of water on Earth has remained roughly the same for billions of years — it just keeps cycling.',
    fun_fact: 'Water molecules that fell as rain 3 million years ago may have been inside dinosaurs, flowed through ancient rivers, frozen into glaciers, and are now in the clouds above you!',
    quiz_question: 'What process turns liquid water into water vapor?',
    quiz_answer: 'Evaporation',
    quiz_options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'Artificial Intelligence: Teaching Machines to Think',
    subtitle: 'How computers learn to recognize faces, win chess, and write stories',
    content: 'Artificial Intelligence (AI) is the simulation of human intelligence processes by machines. Machine learning, a subset of AI, allows computers to learn from data without being explicitly programmed. Deep learning uses neural networks — inspired by the human brain — to recognize patterns in images, speech, and text. AI now powers recommendation systems on Netflix and YouTube, voice assistants like Siri, fraud detection in banks, and medical diagnosis tools. AlphaGo, an AI by DeepMind, defeated the world Go champion in 2016 — a feat once thought impossible as Go has more possible game configurations than atoms in the observable universe.',
    fun_fact: 'The term "Artificial Intelligence" was coined by John McCarthy in 1956, but the concept of thinking machines appeared in ancient myths — like the bronze giant Talos in Greek mythology!',
    quiz_question: 'What type of AI uses layers of neural networks to learn from data?',
    quiz_answer: 'Deep learning',
    quiz_options: ['Deep learning', 'Machine learning', 'Neural networking', 'Quantum computing'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'The Human Brain: The Most Complex Object in the Universe',
    subtitle: 'Understanding the 86 billion neurons inside your head',
    content: 'The human brain contains approximately 86 billion neurons, each connected to thousands of others, creating about 100 trillion synaptic connections. This network processes information faster than the fastest supercomputers for many tasks. The brain uses about 20% of the body\'s energy despite being only 2% of body weight. Different regions handle different functions — the frontal lobe controls decision-making, the hippocampus manages memory, and the cerebellum coordinates movement. Neuroplasticity means the brain can rewire itself based on experiences and learning — even in adulthood.',
    fun_fact: 'The brain has no pain receptors, which is why brain surgery can be performed while the patient is awake — surgeons need the patient to respond to stimuli to avoid damaging critical areas!',
    quiz_question: 'Which part of the brain is primarily responsible for memory formation?',
    quiz_answer: 'Hippocampus',
    quiz_options: ['Hippocampus', 'Amygdala', 'Cerebellum', 'Prefrontal cortex'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'Climate Change: The Science Behind Rising Temperatures',
    subtitle: 'Understanding greenhouse gases and global warming',
    content: 'Climate change refers to long-term shifts in global temperatures and weather patterns. While natural factors cause some change, human activities since the Industrial Revolution have been the main driver. Burning fossil fuels releases carbon dioxide and methane — greenhouse gases that trap heat in the atmosphere like a blanket around Earth. Global average temperature has risen about 1.1°C since pre-industrial times. This seemingly small increase has caused more frequent extreme weather events, rising sea levels (about 3.3mm per year), and melting polar ice. The Arctic is warming 3-4 times faster than the global average. Renewable energy, electric vehicles, and reforestation are key solutions.',
    fun_fact: 'The Great Barrier Reef has lost 50% of its coral since 1995 due to ocean warming — coral bleaching occurs when water becomes too warm and corals expel the algae that give them colour and nutrients!',
    quiz_question: 'What are gases that trap heat in the atmosphere called?',
    quiz_answer: 'Greenhouse gases',
    quiz_options: ['Greenhouse gases', 'Carbon compounds', 'Ozone gases', 'Atmospheric toxins'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'DNA: The Blueprint of Life',
    subtitle: 'How a molecule 2 nanometres wide contains the instructions for all living things',
    content: 'Deoxyribonucleic acid (DNA) is a double-helix molecule that carries genetic information for all living organisms. The human genome contains about 3 billion base pairs encoding approximately 20,000-25,000 genes. DNA is organized into 23 pairs of chromosomes in each human cell nucleus. If you stretched out all the DNA from a single human cell, it would be about 2 metres long. The four chemical bases — adenine, thymine, guanine, and cytosine — pair specifically (A-T, G-C) to form the rungs of the double helix ladder.',
    fun_fact: 'Humans share 60% of their DNA with bananas and 99% with chimpanzees — but even two unrelated humans share 99.9% identical DNA!',
    quiz_question: 'What shape is the DNA molecule?',
    quiz_answer: 'Double helix',
    quiz_options: ['Double helix', 'Triple helix', 'Alpha helix', 'Circular loop'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'The Solar System: Our Cosmic Neighbourhood',
    subtitle: 'Eight planets, millions of asteroids, and one very hot star',
    content: 'Our solar system formed about 4.6 billion years ago from a collapsing cloud of gas and dust. It consists of the Sun (99.86% of all the mass), 8 planets, 5 dwarf planets including Pluto, over 200 moons, millions of asteroids, and billions of comets. The four inner rocky planets (Mercury, Venus, Earth, Mars) are separated from the four outer gas giants (Jupiter, Saturn, Uranus, Neptune) by the asteroid belt. Jupiter\'s Great Red Spot is a storm that has been raging for over 400 years. Saturn\'s rings are made of ice and rock ranging from tiny grains to chunks as large as houses.',
    fun_fact: 'A day on Venus (243 Earth days) is longer than a year on Venus (225 Earth days) — and it rotates backwards compared to most planets!',
    quiz_question: 'Which is the largest planet in our solar system?',
    quiz_answer: 'Jupiter',
    quiz_options: ['Jupiter', 'Saturn', 'Neptune', 'Uranus'],
    topic: 'Space',
    category: 'Science & Tech',
  },
  {
    title: 'The French Revolution: Liberty, Equality, Fraternity',
    subtitle: 'How one uprising changed the concept of government forever',
    content: 'The French Revolution (1789-1799) was a period of radical political and societal transformation in France. Triggered by financial crisis, food shortages, and deep inequality between the aristocracy and common people, the Revolution abolished the monarchy and feudal system. Key events include the storming of the Bastille on July 14, 1789, the Declaration of the Rights of Man and of the Citizen, and the Reign of Terror (1793-94) where over 16,000 people were executed. The Revolution gave rise to Napoleon Bonaparte and spread the ideals of democracy, nationalism, and human rights across Europe and the world.',
    fun_fact: 'The metric system was invented during the French Revolution to replace the chaotic mix of regional measurements — the metre was defined as one ten-millionth of the distance from the North Pole to the equator!',
    quiz_question: 'What famous prison was stormed on July 14, 1789, marking the start of the French Revolution?',
    quiz_answer: 'The Bastille',
    quiz_options: ['The Bastille', 'The Louvre Palace', 'Versailles Palace', 'Notre Dame Cathedral'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Electricity and Magnetism: The Invisible Forces',
    subtitle: 'From lightning bolts to MRI machines',
    content: 'Electricity and magnetism are two aspects of a single fundamental force — electromagnetism. Electric charges in motion create magnetic fields, and changing magnetic fields create electric currents. This principle enables electric generators and motors. Benjamin Franklin\'s famous kite experiment in 1752 showed that lightning is electrical. Electromagnetic waves include radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays. MRI machines use powerful magnetic fields to image the body\'s interior without radiation. The Earth itself acts as a giant magnet, with a molten iron core generating our planet\'s magnetic field.',
    fun_fact: 'The electric eel can generate up to 860 volts of electricity — enough to stun a horse! It uses this to hunt prey and navigate muddy river waters.',
    quiz_question: 'Which scientist discovered electromagnetic induction through his experiments?',
    quiz_answer: 'Michael Faraday',
    quiz_options: ['Michael Faraday', 'Nikola Tesla', 'André-Marie Ampère', 'Alessandro Volta'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'The Silk Road: Ancient Superhighway of Trade',
    subtitle: 'How camels and merchants connected the ancient world',
    content: 'The Silk Road was a network of trade routes connecting China with Central Asia, the Middle East, Africa, and Europe from about 200 BCE to 1450 CE. Named after the Chinese silk traded along its routes, it actually carried much more — spices, glassware, precious metals, paper, gunpowder, and ideas. Buddhism, Islam, and Christianity all spread along the Silk Road. The Black Death pandemic reached Europe via Silk Road traders in 1347. Merchants rarely traveled the entire 6,400 km route — goods passed through many hands. Marco Polo\'s famous travels (1271-1295) helped Europeans understand the wealth and sophistication of Asian civilizations.',
    fun_fact: 'Paper money was invented in China partly because merchants on the Silk Road found it too dangerous and heavy to carry large amounts of copper coins!',
    quiz_question: 'What famous Italian explorer traveled the Silk Road in the 13th century?',
    quiz_answer: 'Marco Polo',
    quiz_options: ['Marco Polo', 'Vasco da Gama', 'Christopher Columbus', 'Ibn Battuta'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Renewable Energy: Powering Tomorrow',
    subtitle: 'How the sun, wind, and water can replace fossil fuels',
    content: 'Renewable energy comes from naturally replenishing sources — solar, wind, hydroelectric, geothermal, and biomass. Solar panels use the photovoltaic effect to convert sunlight into electricity, while wind turbines convert kinetic energy of wind. Renewable energy now provides about 30% of global electricity. The cost of solar panels has dropped 90% in the last decade, making them cheaper than fossil fuels in many places. China is the world\'s largest producer of renewable energy. Iceland gets nearly 100% of its electricity and heating from geothermal and hydroelectric sources.',
    fun_fact: 'The Sahara Desert receives enough solar energy in just 6 hours to power the entire world for a year — covering just 1% of the Sahara with solar panels could supply all of Europe\'s energy needs!',
    quiz_question: 'What effect do solar panels use to convert sunlight into electricity?',
    quiz_answer: 'Photovoltaic effect',
    quiz_options: ['Photovoltaic effect', 'Solar radiation effect', 'Photoelectric conversion', 'Thermal energy transfer'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'Vaccines: The Greatest Public Health Achievement',
    subtitle: 'How a cowpox observation led to saving billions of lives',
    content: 'Vaccines work by training the immune system to recognise and fight specific pathogens without causing disease. Edward Jenner created the first vaccine in 1796 using cowpox to protect against smallpox — the only human disease ever completely eradicated. The immune system responds to a weakened or dead form of a pathogen (or its proteins) by producing antibodies and memory cells. mRNA vaccines, like those developed for COVID-19, teach cells to produce a protein that triggers immunity. Vaccines have eliminated or drastically reduced polio, measles, tetanus, and many other deadly diseases. Global vaccination programs save an estimated 2-3 million lives annually.',
    fun_fact: 'The word "vaccine" comes from "vacca," the Latin word for cow — in honour of the cowpox used in the world\'s first vaccine!',
    quiz_question: 'Who created the first vaccine in 1796?',
    quiz_answer: 'Edward Jenner',
    quiz_options: ['Edward Jenner', 'Louis Pasteur', 'Robert Koch', 'Alexander Fleming'],
    topic: 'Medicine',
    category: 'Science & Tech',
  },
  {
    title: 'Mountains: The Roof of the World',
    subtitle: 'How tectonic forces build Earth\'s highest peaks',
    content: 'Mountains form through tectonic activity — when tectonic plates collide, one plate pushes up against the other, forcing rock upward over millions of years. The Himalayas, home to Mount Everest (8,849m), formed when the Indian subcontinent collided with Eurasia about 50 million years ago and are still rising 5mm per year. Mountains cover 22% of Earth\'s land surface and are home to 13% of the world\'s population. They are crucial water towers — providing 60-80% of the world\'s fresh water. Mountain biodiversity is exceptional: the Andes has over 45,000 plant species.',
    fun_fact: 'Mount Everest is not actually the closest point to space — that\'s Mount Chimborazo in Ecuador, because Earth bulges at the equator!',
    quiz_question: 'What is the tallest mountain on Earth measured from sea level?',
    quiz_answer: 'Mount Everest',
    quiz_options: ['Mount Everest', 'K2', 'Mount Kilimanjaro', 'Mont Blanc'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'The Roman Empire: Engineering the Ancient World',
    subtitle: 'Roads, aqueducts, and concrete that lasted 2,000 years',
    content: 'At its peak around 117 CE, the Roman Empire spanned 5 million square kilometres across Europe, North Africa, and the Middle East, housing about 70 million people. Roman engineering achievements include 80,000 km of roads, aqueducts that brought fresh water to cities, the Colosseum (could hold 80,000 spectators), and concrete using volcanic ash that is still stronger than modern concrete after 2,000 years. Latin evolved into French, Spanish, Portuguese, Italian, and Romanian. Roman law principles underpin most modern legal systems. The calendar we use today is based on Julius Caesar\'s reforms.',
    fun_fact: 'Romans had fast food — archaeologists have found over 80 "thermopolia" (ancient fast food restaurants) in Pompeii, with built-in counters and warm food containers!',
    quiz_question: 'What volcanic material made Roman concrete incredibly durable?',
    quiz_answer: 'Volcanic ash (pozzolana)',
    quiz_options: ['Volcanic ash (pozzolana)', 'Crushed limestone', 'Sea sand', 'Marble powder'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Gravity: The Force That Shapes the Universe',
    subtitle: 'From Newton\'s apple to Einstein\'s spacetime',
    content: 'Gravity is the force that attracts objects with mass toward each other. Isaac Newton described it mathematically in 1687, explaining why apples fall and planets orbit the Sun. Einstein\'s General Theory of Relativity (1915) revolutionised our understanding — gravity is not a force but a curvature in spacetime caused by mass. The more massive an object, the more it warps spacetime around it. This explains why GPS satellites need to correct for time running slightly faster at altitude. Gravitational waves — ripples in spacetime caused by massive accelerating objects — were first detected in 2015 by LIGO, 100 years after Einstein predicted them.',
    fun_fact: 'On the Moon, you would weigh about 1/6 of your Earth weight — an 80kg person would weigh just 13kg!',
    quiz_question: 'According to Einstein, what causes gravity?',
    quiz_answer: 'Curvature in spacetime caused by mass',
    quiz_options: ['Curvature in spacetime caused by mass', 'Magnetic field created by heavy objects', 'Density of matter attracting other matter', 'Energy released by massive objects'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'The Amazon Rainforest: Earth\'s Lungs',
    subtitle: 'The world\'s largest tropical rainforest and its role in climate',
    content: 'The Amazon rainforest covers 5.5 million km² across 9 South American countries, mainly Brazil. It contains 10% of all species on Earth, including 40,000 plant species, 1,300 bird species, and 3,000 fish species. The Amazon River discharges 20% of all fresh water entering the world\'s oceans. The forest creates its own rain through "flying rivers" — trees release so much water vapor that they generate rainfall across the continent. Deforestation threatens this system: Brazil has lost 17% of the Amazon in 50 years.',
    fun_fact: 'The Amazon River was once a river that flowed westward toward the Pacific — until the Andes Mountains rose and blocked its path, forcing it to reverse direction toward the Atlantic!',
    quiz_question: 'What percentage of all fresh water entering the world\'s oceans does the Amazon River discharge?',
    quiz_answer: '20%',
    quiz_options: ['20%', '10%', '30%', '40%'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'The Periodic Table: Chemistry\'s Master Map',
    subtitle: 'How Mendeleev arranged 118 elements into one brilliant chart',
    content: 'Dmitri Mendeleev created the first widely recognised periodic table in 1869, arranging elements by atomic mass and predicting the existence of undiscovered elements. Today\'s table organises 118 confirmed elements by atomic number (protons). Periods (rows) indicate electron shells; groups (columns) share similar chemical properties. Hydrogen is the most abundant element in the universe (75% of all matter). Gold is so unreactive it\'s found as pure metal in nature. Carbon is the basis of all known life and can form more compounds than all other elements combined.',
    fun_fact: 'Element 101, Mendelevium, was created atom by atom — scientists made just 17 atoms in 1955 to confirm its discovery, yet that was enough to determine its chemical properties!',
    quiz_question: 'Who created the first widely recognised periodic table?',
    quiz_answer: 'Dmitri Mendeleev',
    quiz_options: ['Dmitri Mendeleev', 'John Dalton', 'Antoine Lavoisier', 'Henry Moseley'],
    topic: 'Chemistry',
    category: 'Science & Tech',
  },
  {
    title: 'The Industrial Revolution: How Machines Changed Everything',
    subtitle: 'Steam power, factories, and the birth of the modern world',
    content: 'The Industrial Revolution began in Britain around 1760-1840 and spread worldwide, transforming economies from agricultural to industrial. The steam engine, perfected by James Watt, powered factories, trains, and ships. The spinning jenny and power loom mechanized textile production. Urbanization accelerated dramatically — Britain went from 20% urban in 1800 to 80% by 1900. Child labor, 16-hour workdays, and terrible factory conditions led to labor movements and eventual reform. Railways shrank distances: travelling from London to Edinburgh went from 4 days by coach to 8 hours by train.',
    fun_fact: 'The word "luddite" comes from followers of Ned Ludd who smashed textile machines in the 1810s — today it describes anyone opposed to new technology!',
    quiz_question: 'Who perfected the steam engine that powered the Industrial Revolution?',
    quiz_answer: 'James Watt',
    quiz_options: ['James Watt', 'George Stephenson', 'Thomas Edison', 'Isambard Kingdom Brunel'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Quantum Physics: The Weird World of the Very Small',
    subtitle: 'Where particles are in two places at once and cats are both alive and dead',
    content: 'Quantum physics describes the behaviour of matter and energy at the smallest scales — atoms and subatomic particles. Unlike classical physics, quantum mechanics is probabilistic: particles don\'t have definite positions or speeds until measured. Wave-particle duality means electrons behave as waves when not observed but as particles when measured. Quantum entanglement allows particles to be correlated so that measuring one instantly affects the other regardless of distance — Einstein called this "spooky action at a distance." Quantum physics underlies modern technology: semiconductors, lasers, MRI machines, and quantum computers all rely on quantum principles.',
    fun_fact: 'Quantum tunneling allows particles to pass through barriers they shouldn\'t be able to cross — this is how nuclear fusion happens in the Sun and how transistors in your phone work!',
    quiz_question: 'What is it called when two quantum particles are correlated such that measuring one instantly affects the other?',
    quiz_answer: 'Quantum entanglement',
    quiz_options: ['Quantum entanglement', 'Wave-particle duality', 'Quantum superposition', 'Quantum tunneling'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'Democracy: Government by the People',
    subtitle: 'From ancient Athens to modern elections',
    content: 'Democracy originates from the Greek words "demos" (people) and "kratos" (rule). Ancient Athens in the 5th century BCE practiced direct democracy — citizens voted directly on laws, though women and slaves were excluded. Modern representative democracy evolved through Magna Carta (1215), the English Bill of Rights (1689), the American Declaration of Independence (1776), and the French Revolution. Today, 97 countries are considered full or flawed democracies. India is the world\'s largest democracy with over 900 million eligible voters.',
    fun_fact: 'In ancient Athens, they used a machine called a "kleroterion" — a randomizer that selected citizens for jury duty, similar to a modern lottery ball machine!',
    quiz_question: 'In which ancient city was democracy first practiced?',
    quiz_answer: 'Athens',
    quiz_options: ['Athens', 'Rome', 'Sparta', 'Alexandria'],
    topic: 'Politics',
    category: 'Society & Culture',
  },
  {
    title: 'Plate Tectonics: The Earth Is Constantly Moving',
    subtitle: 'How continents drift and why earthquakes and volcanoes occur',
    content: 'The Earth\'s outer layer (lithosphere) is broken into about 15 major tectonic plates floating on the semi-liquid mantle. These plates move 2-15 cm per year. When plates collide, one can subduct beneath the other, creating mountain ranges and ocean trenches. When they pull apart, new seafloor forms. 90% of the world\'s earthquakes happen in the "Ring of Fire" — a horseshoe-shaped zone around the Pacific Ocean. All today\'s continents were once joined as the supercontinent Pangaea, which began breaking apart 175 million years ago.',
    fun_fact: 'Africa and South America fit together like puzzle pieces — the identical fossil species found on both continents helped prove continental drift long before plate tectonic theory was accepted!',
    quiz_question: 'What was the name of the supercontinent that existed before the current continents drifted apart?',
    quiz_answer: 'Pangaea',
    quiz_options: ['Pangaea', 'Gondwana', 'Laurasia', 'Rodinia'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'The Moon Landing: One Giant Leap for Mankind',
    subtitle: 'How humanity first set foot on another world',
    content: 'On July 20, 1969, NASA\'s Apollo 11 mission landed humans on the Moon for the first time. Astronauts Neil Armstrong and Buzz Aldrin spent 2.5 hours on the lunar surface while Michael Collins orbited above. The mission was born from President Kennedy\'s 1961 challenge to land on the Moon before the decade\'s end, during the Space Race with the Soviet Union. The Saturn V rocket remains the most powerful ever built, generating 34.5 million newtons of thrust. The mission computer had less processing power than a modern smartwatch. Six Apollo missions landed a total of 12 astronauts on the Moon between 1969 and 1972.',
    fun_fact: 'Neil Armstrong\'s heartbeat reached 150 beats per minute as he manually guided the lunar module to avoid a crater full of boulders — they landed with only 20 seconds of fuel remaining!',
    quiz_question: 'Who was the first human to set foot on the Moon?',
    quiz_answer: 'Neil Armstrong',
    quiz_options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'],
    topic: 'Space',
    category: 'Science & Tech',
  },
  {
    title: 'The Internet: How the World Got Connected',
    subtitle: 'From ARPANET in 1969 to 5 billion users today',
    content: 'The internet began as ARPANET in 1969, a US military network that could survive nuclear attack by routing data through multiple paths. Tim Berners-Lee invented the World Wide Web in 1989 at CERN, creating HTML, URLs, and HTTP — making the internet accessible to everyone. Today, 5.4 billion people use the internet — 67% of the world\'s population. Every minute, 500 hours of video are uploaded to YouTube, 695,000 stories are shared on Instagram, and 6 million Google searches are made. Undersea fiber-optic cables carry 99% of international internet traffic.',
    fun_fact: 'The first email was sent by Ray Tomlinson in 1971 — and he chose the @ symbol to separate the username from the computer name, a convention we still use 50 years later!',
    quiz_question: 'Who invented the World Wide Web in 1989?',
    quiz_answer: 'Tim Berners-Lee',
    quiz_options: ['Tim Berners-Lee', 'Bill Gates', 'Vint Cerf', 'Steve Jobs'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'Oceans: The Final Frontier on Earth',
    subtitle: 'Why we know more about the Moon\'s surface than our own ocean floors',
    content: 'Oceans cover 71% of Earth\'s surface and contain 97% of the planet\'s water. The five oceans regulate climate, absorb 25% of CO₂ emissions, and produce 50% of Earth\'s oxygen. The deep ocean (below 200m) is the largest habitat on Earth, yet 80% remains unexplored. The Mariana Trench is the deepest point at 11,034m — Mount Everest would fit inside with 2km to spare. Oceans support 2.4 billion people\'s food and livelihoods. Coral reefs, covering just 0.1% of the ocean floor, house 25% of all marine species.',
    fun_fact: 'The Pacific Ocean is larger than all of Earth\'s land area combined — so deep that the average depth is 4,000 metres, where no sunlight reaches and pressure is 400 times that at the surface!',
    quiz_question: 'What is the deepest point in Earth\'s oceans called?',
    quiz_answer: 'Mariana Trench',
    quiz_options: ['Mariana Trench', 'Puerto Rico Trench', 'Java Trench', 'Tonga Trench'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'World War II: The Conflict That Shaped Our World',
    subtitle: 'The deadliest conflict in human history and its lasting impact',
    content: 'World War II (1939-1945) involved over 30 countries and caused an estimated 70-85 million deaths — 3% of the world\'s 1940 population. It began when Nazi Germany, under Adolf Hitler, invaded Poland. The Holocaust resulted in the systematic murder of 6 million Jews and 5-6 million others. The United States joined after Japan\'s surprise attack on Pearl Harbor in December 1941. Key turning points included the Battle of Stalingrad (1942-43), D-Day Normandy landings (June 1944), and Allied advance from both east and west. The war ended in Europe in May 1945 and in Asia in September after the US dropped atomic bombs on Hiroshima and Nagasaki.',
    fun_fact: 'During WWII, the US, UK, and Soviet Union were allies — despite being ideological opposites — purely out of necessity to defeat Nazi Germany and Fascist Japan!',
    quiz_question: 'What event prompted the United States to enter World War II?',
    quiz_answer: 'Japan\'s attack on Pearl Harbor',
    quiz_options: ['Japan\'s attack on Pearl Harbor', 'Germany\'s invasion of Poland', 'Italy\'s declaration of war', 'The fall of France'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Microorganisms: Invisible Giants of Earth',
    subtitle: 'The tiny organisms that run the world',
    content: 'Microorganisms — bacteria, viruses, fungi, and protozoa — are invisible to the naked eye but profoundly shape life on Earth. The human body contains more microbial cells than human cells — about 38 trillion bacteria vs 30 trillion human cells. The gut microbiome influences digestion, immunity, and even mood. Bacteria perform nitrogen fixation, making soil fertile for plants. Microorganisms decompose dead matter, cycling nutrients through ecosystems. Fermentation by bacteria and fungi gives us bread, cheese, yogurt, beer, and antibiotics. Penicillin, discovered accidentally by Alexander Fleming in 1928, revolutionized medicine.',
    fun_fact: 'There are more bacteria in one teaspoon of healthy soil than there are people on Earth — and scientists estimate we have only discovered and named about 1% of all microbial species!',
    quiz_question: 'Who discovered penicillin?',
    quiz_answer: 'Alexander Fleming',
    quiz_options: ['Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Joseph Lister'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'Cryptography: The Art of Secret Messages',
    subtitle: 'From Caesar ciphers to modern encryption protecting your data',
    content: 'Cryptography is the practice of securing information by transforming it into an unreadable form. Julius Caesar used a simple shift cipher — moving each letter by 3 positions. World War II\'s Enigma machine used complex rotor encryption. Alan Turing\'s work breaking Enigma at Bletchley Park shortened the war by an estimated 2-4 years. Modern encryption uses mathematical problems that are easy to compute but practically impossible to reverse — like factoring enormous numbers. HTTPS (the padlock in your browser) uses TLS encryption to secure web traffic.',
    fun_fact: 'The Enigma machine had 158 quintillion possible configurations — yet Turing and his team cracked it using a mechanical computer they called the "Bombe"!',
    quiz_question: 'What mathematician led the team that broke the German Enigma cipher in World War II?',
    quiz_answer: 'Alan Turing',
    quiz_options: ['Alan Turing', 'Charles Babbage', 'John von Neumann', 'Blaise Pascal'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'The Human Immune System: Your Body\'s Army',
    subtitle: 'How your body fights off 60,000 bacteria entering every hour',
    content: 'The immune system is the body\'s defense network against pathogens, cancer cells, and foreign substances. The innate immune system provides immediate, non-specific defense — skin, mucus, fever, and inflammation. The adaptive immune system creates targeted responses — B cells produce antibodies that bind to specific pathogens, while T cells directly attack infected cells. Memory cells remember past infections, enabling faster responses to repeat exposure (the basis of vaccination). The immune system must distinguish self from non-self to avoid attacking the body\'s own tissues — failure causes autoimmune diseases like rheumatoid arthritis.',
    fun_fact: 'Fever actually helps fight infection — even a 1°C rise in body temperature speeds up immune cell activity by 25% and slows down bacterial reproduction!',
    quiz_question: 'What type of immune cells produce antibodies to fight specific pathogens?',
    quiz_answer: 'B cells',
    quiz_options: ['B cells', 'T cells', 'Neutrophils', 'Macrophages'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'India\'s Space Programme: From Bullock Cart to Mars',
    subtitle: 'How ISRO became a world-class space agency on a fraction of NASA\'s budget',
    content: 'The Indian Space Research Organisation (ISRO) was founded in 1969 by Dr Vikram Sarabhai. India\'s first satellite, Aryabhata, was launched in 1975. The Polar Satellite Launch Vehicle (PSLV) became one of the world\'s most reliable rockets. Chandrayaan-1 (2008) discovered water molecules on the Moon. Mangalyaan (Mars Orbiter Mission, 2013) reached Mars on its first attempt — making India the first Asian nation and fourth space agency to do so — at a cost of just $74 million. Chandrayaan-3 (2023) successfully soft-landed near the Moon\'s south pole, making India the fourth country to land on the Moon and the first to land near its south pole.',
    fun_fact: 'ISRO launched 104 satellites in a single rocket in 2017, breaking the world record! Most were small commercial satellites from 14 different countries.',
    quiz_question: 'Which ISRO mission made India the first country to land near the Moon\'s south pole?',
    quiz_answer: 'Chandrayaan-3',
    quiz_options: ['Chandrayaan-3', 'Chandrayaan-2', 'Mangalyaan', 'Gaganyaan'],
    topic: 'Space',
    category: 'Science & Tech',
  },
  {
    title: 'Earthquakes and Tsunamis: Earth\'s Most Destructive Forces',
    subtitle: 'Understanding the science behind nature\'s most powerful events',
    content: 'Earthquakes occur when tectonic plates suddenly slip, releasing energy as seismic waves. The Richter scale measures magnitude logarithmically — a magnitude 7 earthquake is 10 times stronger than magnitude 6. The deadliest recorded earthquake killed 830,000 people in China in 1556. Earthquakes under the ocean floor can displace massive columns of water, creating tsunamis. The 2004 Indian Ocean tsunami, triggered by a magnitude 9.1 earthquake, killed 230,000 people across 14 countries. Tsunami warning systems now monitor ocean buoys and seismic networks to provide early warnings.',
    fun_fact: 'Japan experiences about 1,500 earthquakes per year — their advanced early warning system can send alerts to 100 million phones 40 seconds before shaking reaches a city!',
    quiz_question: 'What scale is commonly used to measure earthquake magnitude?',
    quiz_answer: 'Richter scale',
    quiz_options: ['Richter scale', 'Mercalli scale', 'Beaufort scale', 'Fujita scale'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'Mathematics: The Language of the Universe',
    subtitle: 'Why math describes reality so perfectly',
    content: 'Mathematics is often called the language of the universe because physical laws are expressed mathematically with extraordinary precision. E=mc² elegantly describes mass-energy equivalence. The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13...) appears in flower petals, spiral galaxies, and nautilus shells. Prime numbers — divisible only by 1 and themselves — are infinitely numerous yet seemingly random, used to secure internet encryption. The number π (pi) = 3.14159... appears in circles, waves, and quantum physics. Zero was invented independently in India and Mesoamerica — its introduction revolutionized calculation and made modern science possible.',
    fun_fact: 'Ramanujan, an Indian mathematician with no formal training, sent 120 theorems to a Cambridge professor — many were so advanced they weren\'t proven correct until decades after his death!',
    quiz_question: 'What is the term for numbers divisible only by 1 and themselves?',
    quiz_answer: 'Prime numbers',
    quiz_options: ['Prime numbers', 'Composite numbers', 'Natural numbers', 'Rational numbers'],
    topic: 'Mathematics',
    category: 'Science & Tech',
  },
  {
    title: 'Biodiversity: Why Every Species Matters',
    subtitle: 'The intricate web of life and what happens when species disappear',
    content: 'Biodiversity refers to the variety of life on Earth — estimated 8.7 million species, though only 1.5 million have been formally described. Ecosystems are interdependent webs: removing one species can cascade through the system. When wolves were reintroduced to Yellowstone in 1995, they controlled elk populations, which allowed vegetation to recover, which stabilized riverbanks, which improved habitat for beavers, fish, and birds — called a "trophic cascade." The current extinction rate is 1,000 times higher than natural background rates.',
    fun_fact: 'The rosy periwinkle plant from Madagascar provided two compounds that transformed childhood leukemia survival rates from 10% to 90% — showing the medical value of protecting biodiversity!',
    quiz_question: 'What is it called when the removal of one species causes cascading effects through an ecosystem?',
    quiz_answer: 'Trophic cascade',
    quiz_options: ['Trophic cascade', 'Ecological succession', 'Keystone effect', 'Population dynamics'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'Writing Systems: How Humans Preserved Knowledge',
    subtitle: 'From cave paintings to cuneiform to the alphabet',
    content: 'Writing systems have developed independently multiple times in history. Cuneiform, used in Mesopotamia from about 3400 BCE, is among the oldest — pressed into clay tablets with a reed stylus. Egyptian hieroglyphics used symbols representing sounds and concepts. The Phoenician alphabet (1050 BCE) was the ancestor of most modern alphabets including Greek, Latin, Arabic, and Hebrew. Chinese characters, used continuously for 3,500 years, are the oldest writing system still in use. The Rosetta Stone — found in Egypt in 1799 — allowed scholars to finally decode hieroglyphics.',
    fun_fact: 'The Rosetta Stone had the same text written in three scripts: ancient Egyptian hieroglyphics, Demotic script, and Ancient Greek, allowing scholars to finally decode hieroglyphics!',
    quiz_question: 'What ancient writing system used symbols pressed into clay tablets?',
    quiz_answer: 'Cuneiform',
    quiz_options: ['Cuneiform', 'Hieroglyphics', 'Linear A', 'Proto-Sinaitic'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'The Human Eye: A 576-Megapixel Camera',
    subtitle: 'How your eyes capture light and your brain creates images',
    content: 'The human eye detects light through two types of photoreceptors: 120 million rods (for low-light, black and white vision) and 6-7 million cones (for colour vision in three wavelengths: red, green, blue). The retina converts light into electrical signals sent via the optic nerve to the visual cortex. The brain processes vision — filling in the blind spot, stabilising moving images, and interpreting depth. Human eyes can theoretically distinguish about 10 million different colours. The eye moves about 100,000 times per day in rapid "saccadic" movements that our brain smooths out.',
    fun_fact: 'You have a blind spot where your optic nerve connects to your retina — but your brain fills it in so seamlessly you never notice!',
    quiz_question: 'What are the two types of photoreceptors in the human eye?',
    quiz_answer: 'Rods and cones',
    quiz_options: ['Rods and cones', 'Rods and lenses', 'Cones and cornea', 'Pupils and rods'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'Nuclear Energy: Power of the Stars on Earth',
    subtitle: 'How splitting atoms generates electricity',
    content: 'Nuclear fission — splitting heavy atoms like uranium-235 — releases enormous energy: 1 kg of uranium-235 produces the same energy as 3,000 tonnes of coal. Nuclear power generates about 10% of world electricity with zero direct carbon emissions. France gets 75% of its electricity from nuclear power. Nuclear fusion — combining light atoms like hydrogen — is how the Sun generates energy, and is the basis of hydrogen bombs. Scientists are working on fusion reactors (like ITER in France) that would produce virtually unlimited clean energy with minimal radioactive waste.',
    fun_fact: 'The Sun fuses 620 million tonnes of hydrogen into helium every second — producing the same energy as 4 trillion 1-megaton nuclear bombs detonating simultaneously!',
    quiz_question: 'What process generates energy in nuclear power plants by splitting heavy atoms?',
    quiz_answer: 'Nuclear fission',
    quiz_options: ['Nuclear fission', 'Nuclear fusion', 'Radioactive decay', 'Chain reaction'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'The Mughal Empire: Jewel of the Indian Subcontinent',
    subtitle: 'Art, architecture, and tolerance under India\'s greatest emperors',
    content: 'The Mughal Empire, founded by Babur in 1526, ruled most of the Indian subcontinent for over 300 years. At its peak under Akbar the Great (1556-1605), it was the world\'s largest economy and produced about 25% of global GDP. Akbar\'s Din-i-Ilahi attempted religious synthesis and tolerance across faiths. Shah Jahan built the Taj Mahal (1632-1653) as a mausoleum for his wife Mumtaz Mahal. The Red Fort, Fatehpur Sikri, and many architectural wonders date from this era.',
    fun_fact: 'The Taj Mahal changes colour throughout the day — pinkish in morning, milky white at noon, and golden in the evening!',
    quiz_question: 'Which Mughal emperor is famous for religious tolerance and founding Din-i-Ilahi?',
    quiz_answer: 'Akbar',
    quiz_options: ['Akbar', 'Shah Jahan', 'Aurangzeb', 'Humayun'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Psychology: Understanding the Human Mind',
    subtitle: 'From Freud\'s unconscious to modern cognitive science',
    content: 'Psychology is the scientific study of the mind and behaviour. Sigmund Freud proposed the unconscious mind, defence mechanisms, and psychoanalysis. Ivan Pavlov demonstrated classical conditioning using dogs and bells — showing how associations are learned. B.F. Skinner\'s operant conditioning showed how rewards and punishments shape behaviour. Abraham Maslow\'s hierarchy of needs proposed that basic needs (food, safety) must be met before higher needs (love, self-actualisation). Cognitive biases — systematic errors in thinking — include confirmation bias, the sunk cost fallacy, and the availability heuristic.',
    fun_fact: 'The "Bystander Effect" — where people are less likely to help in an emergency when others are present — was discovered after the murder of Kitty Genovese in 1964!',
    quiz_question: 'What did Pavlov demonstrate using dogs and bells?',
    quiz_answer: 'Classical conditioning',
    quiz_options: ['Classical conditioning', 'Operant conditioning', 'Social learning theory', 'Cognitive dissonance'],
    topic: 'Psychology',
    category: 'Society & Culture',
  },
  {
    title: 'Recycling and Waste Management: The Circular Economy',
    subtitle: 'How to close the loop on waste and resources',
    content: 'The global waste crisis is severe: humans generate 2.01 billion tonnes of municipal solid waste annually. Single-use plastics reach the ocean at 8 million tonnes per year. The circular economy aims to eliminate waste by keeping materials in use: reduce consumption, reuse products, and recycle materials. Recycling aluminium uses 95% less energy than producing it from ore. Composting food waste reduces methane from landfills. Japan achieves 99.9% household sorting with dedicated bins for multiple categories.',
    fun_fact: 'A single aluminium can recycled saves enough energy to run a television for 3 hours. Aluminium can be recycled indefinitely without losing quality!',
    quiz_question: 'What economic model aims to eliminate waste by keeping materials in continuous use?',
    quiz_answer: 'Circular economy',
    quiz_options: ['Circular economy', 'Green economy', 'Sustainable economy', 'Blue economy'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'The Speed of Light: Universe\'s Ultimate Speed Limit',
    subtitle: 'Why nothing can travel faster than 299,792,458 metres per second',
    content: 'The speed of light (c) in a vacuum is 299,792,458 m/s — about 300,000 km/s. Einstein\'s Special Theory of Relativity (1905) showed that c is the universe\'s cosmic speed limit. As an object moves faster, its mass increases and time slows down (time dilation). At the speed of light, time would stop completely. Light from the Sun takes 8 minutes to reach Earth; from the nearest star, 4.24 years. Light from the Andromeda Galaxy takes 2.5 million years — so we see it as it was 2.5 million years ago.',
    fun_fact: 'When you look at the night sky, you\'re looking back in time — the most distant galaxies visible are seen as they were 13 billion years ago, just 700 million years after the Big Bang!',
    quiz_question: 'What is the approximate speed of light in a vacuum?',
    quiz_answer: '300,000 km/s',
    quiz_options: ['300,000 km/s', '186,000 km/s', '150,000 km/s', '450,000 km/s'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'Languages of the World: The Tower of Babel',
    subtitle: 'Why there are 7,000 languages and how they evolve',
    content: 'There are approximately 7,139 languages spoken in the world today, though half are endangered. Languages evolve from a common ancestor through isolation and change — like biological species. All Indo-European languages (English, Hindi, Spanish, Russian, etc.) descended from Proto-Indo-European spoken 5,000-6,000 years ago. Mandarin Chinese has the most native speakers (1 billion), but English is the most widely spoken total (1.5 billion). Papua New Guinea has over 800 languages for 8 million people — the most linguistic diversity anywhere.',
    fun_fact: 'Sanskrit, one of the oldest written languages, has over 96 words for "love," each describing a different nuance — compared to English\'s single word!',
    quiz_question: 'Approximately how many languages are spoken in the world today?',
    quiz_answer: 'About 7,000 languages',
    quiz_options: ['About 7,000 languages', 'About 3,000 languages', 'About 10,000 languages', 'About 5,000 languages'],
    topic: 'Language',
    category: 'Society & Culture',
  },
  {
    title: 'The Digestive System: A 9-Metre Food Processing Plant',
    subtitle: 'How your body extracts energy and nutrients from food',
    content: 'The digestive system breaks down food into nutrients absorbable by the body. Digestion begins in the mouth with chewing and amylase in saliva. Food passes through the 25cm oesophagus to the stomach, where acid (pH 1.5-3.5) and enzymes further break it down. The small intestine (6-7m long) absorbs nutrients through finger-like villi that, if flattened, would cover a tennis court. The large intestine (1.5m) absorbs water and houses the microbiome. An average person processes about 35 tonnes of food in a lifetime.',
    fun_fact: 'Your stomach produces a new lining every 3-5 days — otherwise the hydrochloric acid strong enough to dissolve metal would digest the stomach itself!',
    quiz_question: 'Which organ in the digestive system absorbs most nutrients?',
    quiz_answer: 'Small intestine',
    quiz_options: ['Small intestine', 'Large intestine', 'Stomach', 'Liver'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'World Religions: Humanity\'s Search for Meaning',
    subtitle: 'How the world\'s great faiths began and what they teach',
    content: 'About 84% of the world\'s 8 billion people identify with a religion. Christianity (2.4 billion) and Islam (1.9 billion) are the largest, followed by Hinduism (1.2 billion), Buddhism (500 million), and Judaism (14 million). Hinduism, originating in the Indus Valley around 3000 BCE, is the oldest surviving religion with concepts like dharma, karma, and moksha. Buddhism was founded by Siddhartha Gautama in 5th century BCE India. Islam began in 7th century CE Arabia. All major religions share similar ethical cores: treat others as you wish to be treated.',
    fun_fact: 'The Kumbh Mela, a Hindu pilgrimage in India, is the largest human gathering on Earth — the 2019 event drew 200 million visitors over 50 days, visible from space via satellite!',
    quiz_question: 'What is the oldest continuously practiced religion still existing today?',
    quiz_answer: 'Hinduism',
    quiz_options: ['Hinduism', 'Judaism', 'Zoroastrianism', 'Jainism'],
    topic: 'Culture',
    category: 'History & Culture',
  },
  {
    title: 'Genetic Engineering: Rewriting the Code of Life',
    subtitle: 'CRISPR and the revolution in editing DNA',
    content: 'Genetic engineering allows scientists to directly modify an organism\'s DNA. CRISPR-Cas9, discovered in 2012, acts like molecular scissors — precisely cutting and editing DNA sequences. Potential applications include curing genetic diseases (sickle cell, cystic fibrosis), engineering malaria-resistant mosquitoes, developing drought-resistant crops, and creating new cancer therapies. Golden rice, genetically modified to produce beta-carotene, could prevent vitamin A deficiency affecting 200 million children. The first CRISPR therapy for sickle cell disease was approved in 2023.',
    fun_fact: 'Scientists have used CRISPR to encode a movie into the DNA of living bacteria — demonstrating that DNA could store 215 petabytes of data per gram!',
    quiz_question: 'What gene-editing tool discovered in 2012 is often described as "molecular scissors"?',
    quiz_answer: 'CRISPR-Cas9',
    quiz_options: ['CRISPR-Cas9', 'CRISPR-Cas12', 'Zinc finger nuclease', 'TALEN'],
    topic: 'Biology',
    category: 'Science & Tech',
  },
  {
    title: 'Volcanoes: Earth\'s Natural Pressure Valves',
    subtitle: 'How magma becomes lava and what happens when supervolcanoes erupt',
    content: 'Volcanoes form where magma from the mantle reaches the surface, either at tectonic plate boundaries or "hotspots." There are about 1,500 potentially active volcanoes globally, with 50-70 erupting each year. Lava can reach 1,200°C and flow at 10 km/h. The 1883 Krakatoa eruption was heard 5,000 km away and lowered global temperatures 1.2°C for a year. The Yellowstone Caldera is a supervolcano — a super-eruption would release 1,000 cubic km of material. Iceland, sitting on the Mid-Atlantic Ridge, has 32 active volcanic systems.',
    fun_fact: 'The volcanic eruption of Mount Tambora in 1815 caused "The Year Without a Summer" in 1816, with snowfall in June across North America and Europe!',
    quiz_question: 'What is the term for a massive volcanic crater formed by a collapsed magma chamber?',
    quiz_answer: 'Caldera',
    quiz_options: ['Caldera', 'Crater', 'Vent', 'Magma chamber'],
    topic: 'Geography',
    category: 'Environment',
  },
  {
    title: 'The Age of Exploration: Mapping the Unknown World',
    subtitle: 'How European sailors linked the globe in the 15th and 16th centuries',
    content: 'The Age of Exploration (1400s-1600s) saw European sailors navigating the world\'s oceans for the first time. Portugal\'s Henry the Navigator sponsored expeditions along Africa\'s coast. Vasco da Gama reached India by sea in 1498, establishing a lucrative spice trade route. Columbus\'s 1492 voyage led to European encounter with the Americas. Ferdinand Magellan\'s expedition (1519-1522) circumnavigated the globe, proving Earth was round. These voyages led to the Columbian Exchange — transfer of plants, animals, and diseases between Old and New Worlds.',
    fun_fact: 'Columbus died in 1506 still believing he had reached Asia — it was Amerigo Vespucci who first argued these were "New Worlds," which is why the continents are named America after him!',
    quiz_question: 'Who led the first expedition to circumnavigate the globe?',
    quiz_answer: 'Ferdinand Magellan',
    quiz_options: ['Ferdinand Magellan', 'Christopher Columbus', 'Francis Drake', 'Vasco da Gama'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Sound and Music: The Physics of Harmony',
    subtitle: 'Why some note combinations sound beautiful and others don\'t',
    content: 'Sound is a mechanical wave — vibrations traveling through air (or any medium) as compressions and rarefactions. Frequency determines pitch (440 Hz = A above middle C); amplitude determines loudness. The human ear hears 20 Hz to 20,000 Hz. Music is structured sound — melody, harmony, and rhythm. Pythagoras discovered that musical intervals correspond to simple mathematical ratios: an octave is 2:1, a perfect fifth is 3:2. The brain\'s reward circuits fire when listening to music, releasing dopamine — explaining why music evokes strong emotions.',
    fun_fact: 'Music can reduce cortisol levels by 40%, lower blood pressure, and boost the immune system — hospitals use music therapy to help patients recover faster from surgery!',
    quiz_question: 'What determines the pitch of a sound?',
    quiz_answer: 'Frequency (measured in Hz)',
    quiz_options: ['Frequency (measured in Hz)', 'Amplitude', 'Wavelength', 'Decibels'],
    topic: 'Physics',
    category: 'Arts & Culture',
  },
  {
    title: 'Ancient Civilizations: The Dawn of Humanity',
    subtitle: 'Why four rivers gave rise to four great civilizations simultaneously',
    content: 'The first complex civilizations arose independently around 3000-3500 BCE in four river valleys: Mesopotamia (Tigris-Euphrates), Egypt (Nile), India (Indus), and China (Yellow River). Rivers provided water, fertile soil from floods, and trade routes. All four developed writing, mathematics, organized government, specialization of labor, monumental architecture, and long-distance trade. The Indus Valley Civilization was remarkably advanced — cities like Mohenjo-daro had grid streets, indoor plumbing, and standardized brick sizes.',
    fun_fact: 'The ancient Indus Valley city of Mohenjo-daro had a sophisticated sewage system with covered drains running under streets — better sanitation infrastructure than many ancient cities that came millennia later!',
    quiz_question: 'Which ancient civilization built cities with advanced plumbing and grid-layout streets around 2500 BCE?',
    quiz_answer: 'Indus Valley Civilization',
    quiz_options: ['Indus Valley Civilization', 'Mesopotamian Civilization', 'Egyptian Civilization', 'Chinese Civilization'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Robots and Automation: The Fourth Industrial Revolution',
    subtitle: 'How machines are changing what work means',
    content: 'Robots and automation are transforming manufacturing, agriculture, logistics, and services. Industrial robots perform 3 million tasks per year in car manufacturing with near-zero error rates. Warehouse robots at Amazon pick, pack, and ship millions of items daily. Surgical robots allow precision beyond human hands in complex operations. Self-driving vehicles use sensors, GPS, and AI to navigate roads. The World Economic Forum estimates 85 million jobs will be displaced by automation by 2025, but 97 million new roles will emerge.',
    fun_fact: 'The word "robot" comes from the Czech word "robota" meaning forced labor — coined in a 1920 science fiction play. The first programmable industrial robot, Unimate, was installed at General Motors in 1961!',
    quiz_question: 'What does the Czech word "robota," the origin of the word "robot," mean?',
    quiz_answer: 'Forced labor',
    quiz_options: ['Forced labor', 'Hard worker', 'Metal man', 'Mechanical servant'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'Human Rights: The Universal Declaration',
    subtitle: 'How 30 articles changed what governments owe their citizens',
    content: 'The Universal Declaration of Human Rights (UDHR), adopted by the UN General Assembly on December 10, 1948, was drafted in the aftermath of World War II\'s atrocities. It proclaims 30 fundamental rights including life, liberty, security, education, and freedom from torture and arbitrary arrest. Eleanor Roosevelt chaired the drafting committee. The UDHR is not a binding treaty but has influenced 80+ national constitutions and numerous international treaties. The UN Human Rights Council monitors compliance.',
    fun_fact: 'The Universal Declaration of Human Rights is the world\'s most translated document — available in over 500 languages, from Abkhazian to Zulu!',
    quiz_question: 'Who chaired the committee that drafted the Universal Declaration of Human Rights?',
    quiz_answer: 'Eleanor Roosevelt',
    quiz_options: ['Eleanor Roosevelt', 'Franklin D. Roosevelt', 'René Cassin', 'Hansa Mehta'],
    topic: 'Politics',
    category: 'Society & Culture',
  },
  {
    title: 'Computers: From Room-Sized Machines to Pocket-Sized Supercomputers',
    subtitle: 'How Moore\'s Law transformed computing in 70 years',
    content: 'The first electronic computer, ENIAC (1945), weighed 30 tonnes and filled an entire room. Moore\'s Law — the observation by Intel co-founder Gordon Moore that transistor counts double approximately every 2 years — has held for 60 years, driving exponential increases in computing power. Today\'s smartphones have 100 billion transistors, more computing power than all of NASA\'s 1969 computers combined. The transistor (1947) enabled miniaturization. Silicon Valley is named after silicon semiconductors.',
    fun_fact: 'The Apollo 11 guidance computer that landed humans on the Moon had just 4 KB of RAM and 72 KB of storage — your microwave oven today has more computing power!',
    quiz_question: 'What is Moore\'s Law?',
    quiz_answer: 'Transistor counts in chips double approximately every 2 years',
    quiz_options: ['Transistor counts in chips double approximately every 2 years', 'Computing speed triples every year', 'Memory capacity doubles every 18 months', 'Processor performance doubles every decade'],
    topic: 'Technology',
    category: 'Science & Tech',
  },
  {
    title: 'Migration: Why Humans Have Always Moved',
    subtitle: 'From the first Homo sapiens out of Africa to today\'s global diaspora',
    content: 'Modern Homo sapiens originated in Africa about 300,000 years ago and began migrating globally 60,000-70,000 years ago. They reached Australia 65,000 years ago, Europe 45,000 years ago, and the Americas via the Bering Land Bridge 15,000-20,000 years ago. Today, 281 million people (3.6% of world population) live outside their birth country. Economic migration, conflict, and climate change are main drivers. Remittances — money sent home by migrants — total $702 billion annually, more than three times all foreign aid.',
    fun_fact: 'DNA analysis shows that virtually all non-African humans descend from a single small group of perhaps just 1,000-10,000 people who migrated out of Africa about 60,000-70,000 years ago!',
    quiz_question: 'Where did modern Homo sapiens originate before migrating across the world?',
    quiz_answer: 'Africa',
    quiz_options: ['Africa', 'Middle East', 'Asia', 'Europe'],
    topic: 'History',
    category: 'Society & Culture',
  },
  {
    title: 'The Carbon Cycle: Life\'s Most Important Loop',
    subtitle: 'How carbon moves between atmosphere, oceans, plants, and soil',
    content: 'Carbon is the backbone of all life and cycles continuously through Earth\'s systems. Plants absorb CO₂ through photosynthesis; animals eat plants and release CO₂ through respiration; decomposers return carbon from dead organisms to soil; volcanoes release carbon from the mantle; oceans absorb and release CO₂. This natural cycle kept Earth\'s temperature relatively stable for millions of years. Human activities have disrupted the cycle: burning fossil fuels releases 37 billion tonnes of CO₂ annually. The atmosphere now contains more CO₂ (420 ppm) than at any time in 3 million years.',
    fun_fact: 'Ancient trees sometimes contain radioactive carbon-14 from nuclear weapons tests in the 1950s and 1960s — scientists can identify timber from that era because it has elevated C-14 levels!',
    quiz_question: 'What process do plants use to absorb CO₂ from the atmosphere?',
    quiz_answer: 'Photosynthesis',
    quiz_options: ['Photosynthesis', 'Respiration', 'Decomposition', 'Combustion'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'Ancient India\'s Contributions to the World',
    subtitle: 'Numbers, surgery, chess, yoga, and the concept of zero',
    content: 'Ancient India made extraordinary contributions to world civilization. The decimal number system and concept of zero, developed by Indian mathematicians like Brahmagupta (7th century CE) and transmitted via Arab scholars, transformed mathematics worldwide. Aryabhata in the 5th century CE calculated π to 4 decimal places and proposed Earth rotates on its axis. Sushruta (6th century BCE), "the father of surgery," described 300 surgical procedures and 120 surgical instruments. Chess originated in India as "chaturanga" in the 6th century CE. Yoga, practiced for over 5,000 years, is now practiced by 300 million people globally.',
    fun_fact: 'The concept of zero, developed in India, is one of the greatest intellectual achievements in human history — without it, computing, engineering, and modern science would be impossible!',
    quiz_question: 'Which Indian mathematician is credited with one of the earliest formal uses of zero?',
    quiz_answer: 'Brahmagupta',
    quiz_options: ['Brahmagupta', 'Aryabhata', 'Bhaskara', 'Mahavira'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Endangered Animals: Racing Against Extinction',
    subtitle: 'The species we might lose in our lifetime and what can be done',
    content: 'The IUCN Red List currently lists over 42,000 species as threatened with extinction — 28% of all assessed species. The current extinction rate is 1,000-10,000 times the natural background rate. Among critically endangered species: Amur tigers (500 remaining), Sumatran orangutans (7,300), cross river gorillas (250-300), Javan rhinos (75). Conservation successes show change is possible: humpback whales recovered from near extinction to 80,000. India\'s Project Tiger increased wild tiger numbers from 1,411 in 2006 to 3,167 in 2022.',
    fun_fact: 'India\'s Project Tiger is one of the world\'s greatest conservation success stories — tiger populations nearly tripled in 16 years through protected reserves and anti-poaching enforcement!',
    quiz_question: 'What is the name of the list that classifies species by their extinction risk?',
    quiz_answer: 'IUCN Red List',
    quiz_options: ['IUCN Red List', 'CITES Appendix', 'WWF Endangered List', 'UN Species Register'],
    topic: 'Environment',
    category: 'Environment',
  },
  {
    title: 'Economics 101: How Markets Work',
    subtitle: 'Supply, demand, and why prices change',
    content: 'Economics studies how societies allocate scarce resources. The fundamental concept is supply and demand: when demand exceeds supply, prices rise; when supply exceeds demand, prices fall — until equilibrium is reached. Adam Smith\'s "The Wealth of Nations" (1776) argued that individuals pursuing self-interest in competitive markets create overall societal benefit — the "invisible hand." GDP (Gross Domestic Product) measures a country\'s total economic output. India\'s GDP crossed $3.5 trillion in 2023, making it the 5th largest economy.',
    fun_fact: 'The Big Mac Index, invented by The Economist magazine in 1986, compares currencies by measuring how much a McDonald\'s Big Mac costs in each country — a surprisingly effective gauge of purchasing power!',
    quiz_question: 'What concept did Adam Smith describe where individuals pursuing self-interest benefit society?',
    quiz_answer: 'The invisible hand',
    quiz_options: ['The invisible hand', 'The market force', 'The free hand', 'The economic balance'],
    topic: 'Economics',
    category: 'Society & Culture',
  },
  {
    title: 'Space Exploration\'s Next Frontier: Mars and Beyond',
    subtitle: 'Why humanity is planning to become a multi-planetary species',
    content: 'Mars is 225 million km from Earth and takes 6-9 months to reach. NASA\'s Perseverance rover has been collecting rock samples since 2021, searching for signs of ancient life in Mars\'s dried riverbeds. The atmosphere is 95% CO₂, surface temperature averages -60°C, and intense radiation makes long-term habitation challenging. SpaceX\'s Starship aims to transport 100 people per flight to Mars. Beyond Mars, Jupiter\'s moon Europa has a liquid water ocean beneath its ice shell that may harbour life.',
    fun_fact: 'Mars has the largest volcano in the solar system — Olympus Mons, at 21.9 km high and 600 km wide, is nearly 3 times the height of Everest!',
    quiz_question: 'What is the name of NASA\'s rover collecting samples on Mars since 2021?',
    quiz_answer: 'Perseverance',
    quiz_options: ['Perseverance', 'Curiosity', 'Opportunity', 'Spirit'],
    topic: 'Space',
    category: 'Science & Tech',
  },
  {
    title: 'The Art of Critical Thinking',
    subtitle: 'How to evaluate claims, spot logical fallacies, and think clearly',
    content: 'Critical thinking is the ability to analyse information objectively and make reasoned judgments. Key skills include identifying assumptions, evaluating evidence, recognising logical fallacies, and considering alternative perspectives. Common fallacies include: ad hominem (attacking the person, not the argument), straw man (misrepresenting an argument), false dichotomy (presenting only two options when more exist), and appeal to authority. Scientific thinking requires hypotheses to be falsifiable. Confirmation bias — our tendency to seek information confirming existing beliefs — is the most common thinking error.',
    fun_fact: 'In a famous psychology experiment, students asked to count basketball passes in a video missed a person in a gorilla suit walking through — demonstrating "inattentional blindness"!',
    quiz_question: 'What is the term for our tendency to seek information that confirms our existing beliefs?',
    quiz_answer: 'Confirmation bias',
    quiz_options: ['Confirmation bias', 'Selection bias', 'Anchoring bias', 'Availability heuristic'],
    topic: 'Psychology',
    category: 'Society & Culture',
  },
  {
    title: 'The Ocean\'s Food Web: From Plankton to Whales',
    subtitle: 'How energy flows through marine ecosystems',
    content: 'The ocean food web begins with phytoplankton — microscopic photosynthetic organisms that produce 50% of Earth\'s oxygen. Zooplankton eat phytoplankton; small fish eat zooplankton; larger fish eat small fish; apex predators like sharks, orcas, and tuna sit at the top. Energy transfer up the food chain is inefficient — only 10% of energy passes to the next level. Overfishing has depleted 90% of large predatory fish populations since 1950. Whale falls — when whales die and sink — support unique deep-sea ecosystems for decades.',
    fun_fact: 'Blue whales — the largest animals ever — survive entirely on krill (tiny shrimp-like creatures just 2cm long). A blue whale eats 4 tonnes of krill per day!',
    quiz_question: 'What microscopic organisms form the base of the ocean food web and produce 50% of Earth\'s oxygen?',
    quiz_answer: 'Phytoplankton',
    quiz_options: ['Phytoplankton', 'Zooplankton', 'Bacteria', 'Algae'],
    topic: 'Biology',
    category: 'Environment',
  },
  {
    title: 'How Aeroplanes Fly: The Physics of Flight',
    subtitle: 'Bernoulli, Newton, and the four forces that get you airborne',
    content: 'Aeroplanes fly through four forces: lift (upward), gravity (downward), thrust (forward), and drag (backward). Lift is generated by wings — their curved upper surface makes air travel faster, creating lower pressure above the wing, pushing the plane up (Bernoulli principle). The wing\'s angle of attack also deflects air downward, pushing the plane up by Newton\'s third law. Jet engines compress air, mix it with fuel, and ignite it — the expanding gases provide thrust. The Wright Brothers\' first powered flight in 1903 lasted 12 seconds and covered 37 metres.',
    fun_fact: 'The Wright Brothers\' total flight time in their first day was 97 seconds and 260 metres — that entire flight would fit inside the cabin of a modern Boeing 747, wing-to-wing!',
    quiz_question: 'What principle explains that faster-moving air creates lower pressure, generating lift for aeroplane wings?',
    quiz_answer: 'Bernoulli\'s principle',
    quiz_options: ['Bernoulli\'s principle', 'Newton\'s third law', 'Coanda effect', 'Magnus effect'],
    topic: 'Physics',
    category: 'Science & Tech',
  },
  {
    title: 'Ancient Wonders: Engineering Marvels of the Past',
    subtitle: 'How ancient civilizations built structures that still astonish us today',
    content: 'The Seven Wonders of the Ancient World were celebrated by Greek scholars for their extraordinary architecture. Only the Great Pyramid of Giza survives today. Built around 2560 BCE, it stood as the world\'s tallest structure for 3,800 years at 146.5m. Over 2.3 million stone blocks weighing up to 80 tonnes were transported and placed with precision still not fully understood. Roman concrete used volcanic ash and seawater — the resulting crystalline structures made it self-healing and more durable than modern concrete.',
    fun_fact: 'The Great Pyramid of Giza is aligned to true north with an accuracy of 0.05 degrees — more precise than the Paris Meridian, using only tools available 4,500 years ago!',
    quiz_question: 'Which of the Seven Wonders of the Ancient World is the only one still standing?',
    quiz_answer: 'The Great Pyramid of Giza',
    quiz_options: ['The Great Pyramid of Giza', 'The Colosseum of Rome', 'The Parthenon of Athens', 'The Hanging Gardens of Babylon'],
    topic: 'History',
    category: 'History & Culture',
  },
  {
    title: 'Food and Nutrition: You Are What You Eat',
    subtitle: 'The science behind what your body needs to thrive',
    content: 'Nutrition science studies how food affects health. Macronutrients — carbohydrates, proteins, and fats — provide energy. Carbohydrates are the primary fuel; proteins build and repair tissues; fats support hormone production and brain function. Micronutrients — vitamins and minerals — are required in small amounts but are essential. Vitamin C deficiency causes scurvy; iodine deficiency causes goitre; iron deficiency causes anaemia. The Mediterranean diet — rich in vegetables, fruits, whole grains, legumes, fish, and olive oil — is consistently linked to lower cardiovascular disease and longer life.',
    fun_fact: 'Honey never spoils — archaeologists found 3,000-year-old honey in Egyptian tombs that was still edible! Its low water content and acidic pH make it inhospitable to bacteria.',
    quiz_question: 'What dietary pattern is consistently associated with lower cardiovascular disease rates?',
    quiz_answer: 'Mediterranean diet',
    quiz_options: ['Mediterranean diet', 'DASH diet', 'Ketogenic diet', 'Paleo diet'],
    topic: 'Health',
    category: 'Society & Culture',
  },
  {
    title: 'Cities: How Urban Life Shapes Humanity',
    subtitle: 'From ancient Rome to Tokyo\'s 38 million people',
    content: 'Cities are humanity\'s greatest social invention. In 1800, only 2% of people lived in cities; today, 56% do — 4.4 billion people. By 2050, 70% will be urban. Cities generate 80% of global GDP despite covering just 3% of land. Tokyo (38 million) and Delhi (33 million) are the world\'s largest metro areas. Mumbai will be the largest by 2050. Urbanization generally improves living standards through agglomeration effects — clustering people enables specialization, innovation, and efficient service delivery.',
    fun_fact: 'Tokyo has a recycling rate of over 80% and its famous efficient subway system serves 40 million passengers daily with average delays of under 1 minute!',
    quiz_question: 'What percentage of the world\'s population currently lives in cities?',
    quiz_answer: 'About 56%',
    quiz_options: ['About 56%', 'About 40%', 'About 70%', 'About 30%'],
    topic: 'Geography',
    category: 'Society & Culture',
  },
]

export function getTodaysTopic(date?: Date): NewspaperTopic {
  const d = date ?? new Date()
  const start = new Date(d.getFullYear(), 0, 0)
  const diff = d.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / 86400000)
  return NEWSPAPER_TOPICS[dayOfYear % NEWSPAPER_TOPICS.length]
}
