export type TopicEntry = { topic_name: string; topic_order: number }
export type ChapterEntry = { chapter_name: string; chapter_order: number; topics: TopicEntry[] }
export type SubjectEntry = { subject: string; chapters: ChapterEntry[] }
export type GradeEntry = { grade: string; subjects: SubjectEntry[] }
export type BoardData = { board: string; label: string; grades: GradeEntry[] }

// ─── Helper ───────────────────────────────────────────────────────────────────
function topics(...names: string[]): TopicEntry[] {
  return names.map((topic_name, i) => ({ topic_name, topic_order: i + 1 }))
}
function chapter(chapter_name: string, chapter_order: number, ...topicNames: string[]): ChapterEntry {
  return { chapter_name, chapter_order, topics: topics(...topicNames) }
}
function subject(name: string, chapters: ChapterEntry[]): SubjectEntry {
  return { subject: name, chapters }
}

// ─── CBSE ─────────────────────────────────────────────────────────────────────
const CBSE: BoardData = {
  board: 'CBSE',
  label: 'CBSE (NCERT)',
  grades: [
    {
      grade: '6',
      subjects: [
        subject('Mathematics', [
          chapter('Knowing Our Numbers', 1, 'Large Numbers', 'Comparing Numbers', 'Estimation', 'Roman Numerals'),
          chapter('Whole Numbers', 2, 'Natural Numbers & Whole Numbers', 'Number Line', 'Properties of Whole Numbers', 'Patterns in Whole Numbers'),
          chapter('Playing with Numbers', 3, 'Factors and Multiples', 'Prime and Composite Numbers', 'HCF and LCM', 'Prime Factorisation'),
          chapter('Basic Geometrical Ideas', 4, 'Points Lines and Segments', 'Angles', 'Triangles', 'Quadrilaterals', 'Circles'),
          chapter('Understanding Elementary Shapes', 5, 'Measuring Line Segments', 'Angles and Their Types', 'Perpendicular Lines', 'Classification of Triangles', 'Polygons', '3D Shapes'),
          chapter('Integers', 6, 'Negative Numbers', 'Integers on Number Line', 'Addition of Integers', 'Subtraction of Integers'),
          chapter('Fractions', 7, 'Types of Fractions', 'Equivalent Fractions', 'Comparing Fractions', 'Addition and Subtraction of Fractions'),
          chapter('Decimals', 8, 'Tenths and Hundredths', 'Comparing Decimals', 'Addition of Decimals', 'Subtraction of Decimals'),
          chapter('Data Handling', 9, 'Recording Data', 'Pictograph', 'Bar Graph', 'Tally Marks'),
          chapter('Mensuration', 10, 'Perimeter of Shapes', 'Area of Rectangle', 'Area of Square'),
          chapter('Algebra', 11, 'Introduction to Variables', 'Expressions with Variables', 'Simple Equations'),
          chapter('Ratio and Proportion', 12, 'Ratio', 'Proportion', 'Unitary Method'),
          chapter('Symmetry', 13, 'Line Symmetry', 'Lines of Symmetry for Regular Polygons', 'Rotational Symmetry'),
          chapter('Practical Geometry', 14, 'Drawing Line Segments', 'Drawing Perpendicular Lines', 'Drawing Angles', 'Drawing Circles'),
        ]),
        subject('Science', [
          chapter('Food: Where Does It Come From?', 1, 'Sources of Food', 'Plant Parts as Food', 'Animal Products as Food'),
          chapter('Components of Food', 2, 'Nutrients in Food', 'Balanced Diet', 'Deficiency Diseases'),
          chapter('Fibre to Fabric', 3, 'Types of Fibres', 'From Fibre to Yarn', 'From Yarn to Fabric'),
          chapter('Sorting Materials into Groups', 4, 'Properties of Materials', 'Grouping Materials'),
          chapter('Separation of Substances', 5, 'Methods of Separation', 'Threshing Winnowing Sieving', 'Sedimentation Filtration Evaporation'),
          chapter('Changes Around Us', 6, 'Reversible Changes', 'Irreversible Changes'),
          chapter('Getting to Know Plants', 7, 'Types of Plants', 'Stem Root Leaf Functions', 'Flowers and Their Parts'),
          chapter('Body Movements', 8, 'Bones and Skeleton', 'Joints and Their Types', 'Earthworm Cockroach Snail Fish Bird Movement'),
          chapter('The Living Organisms and Their Surroundings', 9, 'Habitat and Adaptation', 'Terrestrial Habitats', 'Aquatic Habitats'),
          chapter('Motion and Measurement of Distances', 10, 'Standard Units of Measurement', 'Measurement of Length', 'Types of Motion'),
          chapter('Light Shadows and Reflections', 11, 'Sources of Light', 'Transparent Translucent Opaque Objects', 'Shadows', 'Mirrors and Reflections'),
          chapter('Electricity and Circuits', 12, 'Electric Cell and Bulb', 'Electric Circuit', 'Conductors and Insulators'),
          chapter('Fun with Magnets', 13, 'Properties of Magnets', 'Magnetic and Non-Magnetic Materials', 'Finding Directions with Magnets'),
          chapter('Water', 14, 'Sources of Water', 'Water Cycle', 'Water Conservation'),
          chapter('Air Around Us', 15, 'Components of Air', 'Importance of Air', 'Oxygen and Carbon Dioxide'),
          chapter('Garbage In Garbage Out', 16, 'Types of Waste', 'Composting', 'Recycling and Reuse'),
        ]),
        subject('Social Science', [
          chapter('What Where How and When?', 1, 'Sources of History', 'Dates and Timeline'),
          chapter('On the Trail of the Earliest People', 2, 'Hunter Gatherers', 'Tools and Fire', 'Cave Paintings'),
          chapter('From Gathering to Growing Food', 3, 'Beginning of Farming', 'Domestication of Animals', 'Settlements'),
          chapter('In the Earliest Cities', 4, 'Harappan Civilisation', 'Town Planning', 'Trade and Crafts'),
          chapter('What Books and Burials Tell Us', 5, 'Vedas', 'Megaliths', 'Life in Vedic Times'),
          chapter('Kingdoms Kings and an Early Republic', 6, 'Janapadas and Mahajanapadas', 'Magadha', 'Vajji Republic'),
          chapter('New Questions and Ideas', 7, 'Upanishads', 'Buddhism', 'Jainism'),
          chapter('The Earth in the Solar System', 8, 'Solar System', 'The Moon', 'Stars and Constellations'),
          chapter('Globe Latitudes and Longitudes', 9, 'Globe', 'Latitudes', 'Longitudes', 'Time Zones'),
          chapter('Motions of the Earth', 10, 'Rotation and Day-Night', 'Revolution and Seasons'),
          chapter('Maps', 11, 'Types of Maps', 'Components of Maps', 'Scale'),
          chapter('Major Domains of the Earth', 12, 'Lithosphere', 'Hydrosphere', 'Atmosphere', 'Biosphere'),
          chapter('Understanding Diversity', 13, 'Diversity in India', 'Unity in Diversity'),
          chapter('What is Government?', 14, 'Levels of Government', 'Democratic Government'),
        ]),
        subject('English', [
          chapter('Who Did Patricks Homework?', 1, 'Reading Comprehension', 'Vocabulary', 'Grammar: Nouns'),
          chapter('How the Dog Found Itself a Master', 2, 'Story Analysis', 'Grammar: Pronouns'),
          chapter('Taro\'s Reward', 3, 'Values and Morals', 'Grammar: Adjectives'),
          chapter('An Indian American Woman in Space', 4, 'Biography Reading', 'Grammar: Verbs'),
          chapter('A Different Kind of School', 5, 'Descriptive Reading', 'Grammar: Adverbs'),
          chapter('Who I Am', 6, 'Self-Expression', 'Grammar: Prepositions'),
          chapter('Fair Play', 7, 'Story Values', 'Grammar: Conjunctions'),
          chapter('A Game of Chance', 8, 'Narrative Skills', 'Grammar: Tenses'),
          chapter('Desert Animals', 9, 'Informational Text', 'Grammar: Articles'),
          chapter('The Banyan Tree', 10, 'Nature Writing', 'Grammar: Punctuation', 'Writing: Paragraph'),
        ]),
      ],
    },
    {
      grade: '7',
      subjects: [
        subject('Mathematics', [
          chapter('Integers', 1, 'Properties of Integers', 'Multiplication of Integers', 'Division of Integers'),
          chapter('Fractions and Decimals', 2, 'Multiplication of Fractions', 'Division of Fractions', 'Multiplication of Decimals', 'Division of Decimals'),
          chapter('Data Handling', 3, 'Mean Median Mode', 'Bar Graphs', 'Probability'),
          chapter('Simple Equations', 4, 'Setting Up Equations', 'Solving Simple Equations', 'Applications'),
          chapter('Lines and Angles', 5, 'Complementary and Supplementary Angles', 'Adjacent and Vertically Opposite Angles', 'Pairs of Lines', 'Transversal'),
          chapter('The Triangle and Its Properties', 6, 'Medians and Altitudes', 'Angle Sum Property', 'Exterior Angle Property', 'Pythagoras Property'),
          chapter('Congruence of Triangles', 7, 'Congruent Figures', 'Criteria for Congruence: SSS SAS ASA RHS'),
          chapter('Comparing Quantities', 8, 'Equivalent Ratios', 'Percentage', 'Profit and Loss', 'Simple Interest'),
          chapter('Rational Numbers', 9, 'Introduction to Rational Numbers', 'Rational Numbers on Number Line', 'Operations on Rational Numbers'),
          chapter('Practical Geometry', 10, 'Constructing Triangles', 'Drawing Parallel Lines'),
          chapter('Perimeter and Area', 11, 'Area of Parallelogram', 'Area of Triangle', 'Circles: Circumference and Area'),
          chapter('Algebraic Expressions', 12, 'Terms Factors Coefficients', 'Like and Unlike Terms', 'Addition and Subtraction of Expressions'),
          chapter('Exponents and Powers', 13, 'Exponents', 'Laws of Exponents', 'Expressing Large Numbers in Standard Form'),
          chapter('Symmetry', 14, 'Lines of Symmetry', 'Rotational Symmetry'),
          chapter('Visualising Solid Shapes', 15, 'Plane and Solid Figures', 'Faces Edges Vertices', 'Nets of Solids'),
        ]),
        subject('Science', [
          chapter('Nutrition in Plants', 1, 'Modes of Nutrition', 'Photosynthesis', 'Parasitic and Saprophytic Nutrition', 'Insectivorous Plants'),
          chapter('Nutrition in Animals', 2, 'Digestion in Humans', 'Digestion in Amoeba', 'Digestion in Ruminants'),
          chapter('Fibre to Fabric', 3, 'Wool', 'Silk', 'Life Cycle of Silkworm'),
          chapter('Heat', 4, 'Temperature and Thermometer', 'Transfer of Heat', 'Types of Clothing in Different Seasons'),
          chapter('Acids Bases and Salts', 5, 'Acids and Bases', 'Natural Indicators', 'Neutralisation', 'Uses of Acids and Bases'),
          chapter('Physical and Chemical Changes', 6, 'Physical Changes', 'Chemical Changes', 'Rusting'),
          chapter('Weather Climate and Adaptations', 7, 'Weather and Climate', 'Climatic Zones', 'Animal Adaptations'),
          chapter('Winds Storms and Cyclones', 8, 'Air Pressure', 'Wind Speed', 'Cyclones and Destruction'),
          chapter('Soil', 9, 'Soil Profile', 'Types of Soil', 'Soil and Crops', 'Soil Erosion'),
          chapter('Respiration in Organisms', 10, 'Types of Respiration', 'Breathing in Humans', 'Respiration in Animals and Plants'),
          chapter('Transportation in Animals and Plants', 11, 'Circulatory System', 'Transport in Plants', 'Excretion'),
          chapter('Reproduction in Plants', 12, 'Modes of Reproduction', 'Sexual Reproduction', 'Seed Dispersal'),
          chapter('Motion and Time', 13, 'Speed', 'Measurement of Time', 'Distance-Time Graph'),
          chapter('Electric Current and Its Effects', 14, 'Symbols in Circuit Diagram', 'Heating Effect', 'Magnetic Effect', 'Electromagnets'),
          chapter('Light', 15, 'Reflection of Light', 'Plane Mirror Images', 'Spherical Mirrors', 'Lenses'),
          chapter('Water: A Precious Resource', 16, 'Water Table', 'Depletion of Water', 'Water Management'),
          chapter('Forests: Our Lifeline', 17, 'Layers of Forest', 'Products of Forests', 'Importance of Forests'),
          chapter('Wastewater Story', 18, 'Sewage Treatment', 'Waterborne Diseases', 'Sanitation'),
        ]),
        subject('Social Science', [
          chapter('Tracing Changes Through a Thousand Years', 1, 'New Sources of History', 'Maps and Their Changes', 'Emergence of New Regions'),
          chapter('New Kings and Kingdoms', 2, 'Military Conquests', 'Administration', 'Prashastis and Land Grants'),
          chapter('The Delhi Sultans', 3, 'The Struggle for Power', 'Administration of Delhi Sultans', 'The Khalji Revolution'),
          chapter('The Mughal Empire', 4, 'Mughal Military Campaigns', 'Mughal Administration', 'Mansabdari System'),
          chapter('Rulers and Buildings', 5, 'Engineering Skills', 'Temples and Mosques', 'Landscape and Gardens'),
          chapter('Towns Traders and Craftspersons', 6, 'Temple Towns', 'Trade and Traders', 'Crafts and Manufacturing'),
          chapter('Environment', 7, 'Natural Environment', 'Human Environment', 'Human Modified Environment'),
          chapter('Our Changing Earth', 8, 'Interior of Earth', 'Earthquakes and Volcanoes', 'Rocks and Soil'),
          chapter('Air', 9, 'Composition of Atmosphere', 'Layers of Atmosphere', 'Weather and Climate'),
          chapter('Water', 10, 'Freshwater Resources', 'Oceans', 'Water Cycle'),
          chapter('Natural Vegetation and Wildlife', 11, 'Types of Vegetation', 'Wildlife', 'Biosphere Reserve'),
          chapter('On Equality', 12, 'Equality in Democracy', 'Midday Meal Scheme', 'Equal Rights'),
          chapter('Role of the Government in Health', 13, 'Public Health', 'Government Hospitals', 'Healthcare System'),
        ]),
        subject('English', [
          chapter('Three Questions', 1, 'Reading and Comprehension', 'Grammar: Sentences'),
          chapter('A Gift of Chappals', 2, 'Story Analysis', 'Grammar: Nouns and Pronouns'),
          chapter('Gopal and the Hilsa Fish', 3, 'Humour in Literature', 'Grammar: Adjectives and Adverbs'),
          chapter('The Ashes That Made Trees Bloom', 4, 'Values', 'Grammar: Tenses'),
          chapter('Quality', 5, 'Dedication and Craft', 'Grammar: Degrees of Comparison'),
          chapter('Expert Detectives', 6, 'Mystery Reading', 'Grammar: Modal Verbs'),
          chapter('The Invention of Vita-Wonk', 7, 'Creative Writing', 'Grammar: Prepositions'),
          chapter('A Homage to Our Brave Soldiers', 8, 'Poetry Analysis', 'Grammar: Active and Passive Voice'),
        ]),
      ],
    },
    {
      grade: '8',
      subjects: [
        subject('Mathematics', [
          chapter('Rational Numbers', 1, 'Properties of Rational Numbers', 'Rational Numbers on Number Line', 'Finding Rational Numbers Between Two Numbers'),
          chapter('Linear Equations in One Variable', 2, 'Solving Linear Equations', 'Applications of Linear Equations', 'Equations Reducible to Linear Form'),
          chapter('Understanding Quadrilaterals', 3, 'Polygons', 'Properties of Parallelograms', 'Rectangle Rhombus Square', 'Kite'),
          chapter('Practical Geometry', 4, 'Constructing Quadrilaterals'),
          chapter('Data Handling', 5, 'Organising Data', 'Pie Charts', 'Chance and Probability'),
          chapter('Squares and Square Roots', 6, 'Properties of Square Numbers', 'Finding Square Roots: Repeated Subtraction and Division'),
          chapter('Cubes and Cube Roots', 7, 'Perfect Cubes', 'Finding Cube Roots'),
          chapter('Comparing Quantities', 8, 'Percentage', 'Profit Loss Discount', 'Simple and Compound Interest', 'GST'),
          chapter('Algebraic Expressions and Identities', 9, 'Terms Factors Coefficients', 'Multiplication of Algebraic Expressions', 'Standard Identities'),
          chapter('Visualising Solid Shapes', 10, 'Views of 3D Shapes', 'Mapping Space Around Us', 'Faces Edges Vertices: Euler\'s Formula'),
          chapter('Mensuration', 11, 'Area of Trapezium', 'Area of General Quadrilateral', 'Surface Area of Cuboid Cube Cylinder', 'Volume of Cuboid Cube Cylinder'),
          chapter('Exponents and Powers', 12, 'Powers with Negative Exponents', 'Laws of Exponents', 'Standard Form'),
          chapter('Direct and Inverse Proportions', 13, 'Direct Proportion', 'Inverse Proportion'),
          chapter('Factorisation', 14, 'Common Factors', 'Factorisation by Regrouping', 'Factorisation Using Identities', 'Division of Algebraic Expressions'),
          chapter('Introduction to Graphs', 15, 'Bar Graph Pie Chart Histogram', 'Linear Graphs', 'Distance-Time Graph'),
          chapter('Playing with Numbers', 16, 'Numbers in General Form', 'Games with Numbers', 'Divisibility Tests'),
        ]),
        subject('Science', [
          chapter('Crop Production and Management', 1, 'Agricultural Practices', 'Irrigation', 'Fertilisers and Manures', 'Crop Protection', 'Food Storage'),
          chapter('Microorganisms: Friend and Foe', 2, 'Types of Microorganisms', 'Useful Microorganisms', 'Harmful Microorganisms', 'Food Preservation'),
          chapter('Synthetic Fibres and Plastics', 3, 'Types of Synthetic Fibres', 'Characteristics of Plastics', 'Plastics and Environment'),
          chapter('Materials: Metals and Non-Metals', 4, 'Properties of Metals', 'Properties of Non-Metals', 'Uses of Metals and Non-Metals'),
          chapter('Coal and Petroleum', 5, 'Natural Resources', 'Coal', 'Petroleum', 'Natural Gas', 'Conservation'),
          chapter('Combustion and Flame', 6, 'Conditions for Combustion', 'Types of Combustion', 'Structure of Flame', 'Fuel Efficiency'),
          chapter('Conservation of Plants and Animals', 7, 'Deforestation', 'Conservation of Forests', 'Biosphere Reserve', 'Wildlife Sanctuary', 'National Park'),
          chapter('Cell Structure and Functions', 8, 'Discovery of Cell', 'Cell Parts', 'Plant Cell vs Animal Cell', 'Unicellular and Multicellular'),
          chapter('Reproduction in Animals', 9, 'Modes of Reproduction', 'Sexual Reproduction', 'Fertilisation', 'Development of Embryo'),
          chapter('Reaching the Age of Adolescence', 10, 'Puberty Changes', 'Hormones', 'Reproductive Health', 'Nutritional Needs'),
          chapter('Force and Pressure', 11, 'Force and Its Effects', 'Pressure', 'Pressure in Fluids', 'Atmospheric Pressure'),
          chapter('Friction', 12, 'Types of Friction', 'Factors Affecting Friction', 'Increasing and Decreasing Friction', 'Fluid Friction'),
          chapter('Sound', 13, 'Vibration and Sound', 'Characteristics of Sound', 'Amplitude Frequency Loudness Pitch', 'Noise Pollution'),
          chapter('Chemical Effects of Electric Current', 14, 'Conduction in Liquids', 'Electrolysis', 'Electroplating'),
          chapter('Some Natural Phenomena', 15, 'Lightning', 'Earthing', 'Earthquakes'),
          chapter('Light', 16, 'Laws of Reflection', 'Regular and Diffused Reflection', 'Multiple Reflections', 'Human Eye', 'Care of Eyes'),
          chapter('Stars and the Solar System', 17, 'Stars', 'Constellations', 'Solar System', 'Moon'),
          chapter('Pollution of Air and Water', 18, 'Air Pollution', 'Water Pollution', 'Potable Water'),
        ]),
        subject('Social Science', [
          chapter('How When and Where', 1, 'Colonialism and Sources', 'Survey and Census'),
          chapter('From Trade to Territory', 2, 'East India Company', 'Battle of Plassey', 'Company\'s Policies'),
          chapter('Ruling the Countryside', 3, 'Permanent Settlement', 'Ryotwari and Mahalwari Systems', 'Impact on Peasants'),
          chapter('Tribals Dikus and the Vision of a Golden Age', 4, 'Tribal Groups', 'Birsa Munda Movement'),
          chapter('When People Rebel', 5, 'Sepoy Mutiny', 'Civilian Uprisings', 'Aftermath of 1857'),
          chapter('Colonialism and the City', 6, 'New Delhi', 'Colonial Architecture', 'Urban Life Changes'),
          chapter('Resources', 7, 'Types of Resources', 'Sustainable Development'),
          chapter('Land Soil Water Natural Vegetation and Wildlife', 8, 'Land Use', 'Soil Types', 'Water Resources', 'Deforestation'),
          chapter('Mineral and Power Resources', 9, 'Types of Minerals', 'Mining', 'Power Resources'),
          chapter('Agriculture', 10, 'Types of Farming', 'Crops and Their Distribution', 'Agricultural Development'),
          chapter('Industries', 11, 'Types of Industries', 'Location Factors', 'Industrial Pollution'),
          chapter('Human Resources', 12, 'Population Distribution', 'Population Density', 'Population Growth'),
          chapter('The Indian Constitution', 13, 'Why a Constitution', 'Key Features', 'Fundamental Rights'),
          chapter('Understanding Secularism', 14, 'What is Secularism', 'Indian Secularism'),
          chapter('Why Do We Need a Parliament?', 15, 'Making Decisions', 'Parliament of India', 'Role of Citizens'),
          chapter('Understanding Laws', 16, 'Rule of Law', 'Unpopular Laws', 'Safeguards Against Misuse'),
        ]),
        subject('English', [
          chapter('The Best Christmas Present in the World', 1, 'Reading', 'Grammar: Tenses Review'),
          chapter('The Tsunami', 2, 'Factual Reading', 'Grammar: Reported Speech'),
          chapter('Glimpses of the Past', 3, 'Comic Strip Reading', 'Grammar: Passive Voice'),
          chapter('Bepin Choudhury\'s Lapse of Memory', 4, 'Fiction Reading', 'Grammar: Conditionals'),
          chapter('The Summit Within', 5, 'Autobiographical Writing', 'Grammar: Adjective Clauses'),
          chapter('This is Jody\'s Fawn', 6, 'Animal Story', 'Grammar: Adverb Clauses'),
          chapter('A Visit to Cambridge', 7, 'Interview Reading', 'Writing: Interview'),
          chapter('A Short Monsoon Diary', 8, 'Diary Writing', 'Writing: Diary Entry'),
        ]),
      ],
    },
    {
      grade: '9',
      subjects: [
        subject('Mathematics', [
          chapter('Number Systems', 1, 'Rational and Irrational Numbers', 'Real Numbers on Number Line', 'Laws of Exponents for Real Numbers'),
          chapter('Polynomials', 2, 'Polynomials in One Variable', 'Zeroes of a Polynomial', 'Remainder Theorem', 'Factor Theorem', 'Algebraic Identities'),
          chapter('Coordinate Geometry', 3, 'Cartesian Plane', 'Plotting Points', 'Distance Formula Basics'),
          chapter('Linear Equations in Two Variables', 4, 'Linear Equations', 'Solutions of Linear Equations', 'Graph of a Linear Equation'),
          chapter('Introduction to Euclid\'s Geometry', 5, 'Euclid\'s Definitions', 'Axioms and Postulates'),
          chapter('Lines and Angles', 6, 'Angle Sum Property', 'Parallel Lines and Transversal', 'Linear Pair'),
          chapter('Triangles', 7, 'Congruence Rules: SSS SAS AAS RHS', 'Properties of Triangle', 'Inequalities in Triangle'),
          chapter('Quadrilaterals', 8, 'Properties of Parallelogram', 'Midpoint Theorem'),
          chapter('Areas of Parallelograms and Triangles', 9, 'Figures on Same Base', 'Area Theorems'),
          chapter('Circles', 10, 'Chords and Their Properties', 'Arcs', 'Cyclic Quadrilateral'),
          chapter('Constructions', 11, 'Angle Bisectors', 'Perpendicular Bisector', 'Constructing Triangles'),
          chapter('Heron\'s Formula', 12, 'Area of Triangle Using Heron\'s Formula', 'Area of Quadrilaterals'),
          chapter('Surface Areas and Volumes', 13, 'Surface Area and Volume of Cuboid Cube', 'Cylinder Cone Sphere Hemisphere'),
          chapter('Statistics', 14, 'Data Collection', 'Bar Graph Histogram Frequency Polygon', 'Mean Median Mode'),
          chapter('Probability', 15, 'Probability of Events', 'Experimental Probability'),
        ]),
        subject('Science', [
          chapter('Matter in Our Surroundings', 1, 'States of Matter', 'Evaporation', 'Latent Heat'),
          chapter('Is Matter Around Us Pure?', 2, 'Mixtures and Solutions', 'Colloids and Suspensions', 'Separation Techniques', 'Physical and Chemical Changes'),
          chapter('Atoms and Molecules', 3, 'Laws of Chemical Combination', 'Dalton\'s Atomic Theory', 'Atoms and Molecules', 'Mole Concept'),
          chapter('Structure of the Atom', 4, 'Charged Particles in Matter', 'Thomson\'s and Rutherford\'s Models', 'Bohr\'s Model', 'Valency and Atomic Number'),
          chapter('The Fundamental Unit of Life', 5, 'Cell Theory', 'Cell Organelles', 'Plant vs Animal Cell', 'Cell Division'),
          chapter('Tissues', 6, 'Plant Tissues', 'Animal Tissues'),
          chapter('Diversity in Living Organisms', 7, 'Classification of Organisms', 'Kingdoms of Life', 'Nomenclature'),
          chapter('Motion', 8, 'Uniform and Non-Uniform Motion', 'Speed Velocity Acceleration', 'Equations of Motion', 'Circular Motion'),
          chapter('Force and Newton\'s Laws', 9, 'Newton\'s First Second Third Law', 'Inertia', 'Momentum'),
          chapter('Gravitation', 10, 'Universal Law of Gravitation', 'Free Fall', 'Weight and Mass', 'Thrust and Pressure', 'Archimedes\' Principle'),
          chapter('Work and Energy', 11, 'Work Done', 'Energy: Kinetic and Potential', 'Law of Conservation of Energy', 'Power'),
          chapter('Sound', 12, 'Propagation of Sound', 'Characteristics of Sound Wave', 'Reflection of Sound', 'Ultrasound Applications'),
          chapter('Why Do We Fall Ill?', 13, 'Health and Disease', 'Infectious Diseases', 'Organ Specific Manifestation', 'Prevention'),
          chapter('Natural Resources', 14, 'Air Water Soil', 'Cycles in Nature', 'Ozone Layer'),
          chapter('Improvement in Food Resources', 15, 'Crop Improvement', 'Crop Production', 'Animal Husbandry', 'Poultry Fisheries Apiculture'),
        ]),
        subject('Social Science', [
          chapter('The Story of Village Palampur', 1, 'Farming in Palampur', 'Other Activities', 'Capital and Labour'),
          chapter('People as Resource', 2, 'Human Capital Formation', 'Economic Activities', 'Unemployment'),
          chapter('Poverty as a Challenge', 3, 'Poverty Line', 'Vulnerable Groups', 'Anti-Poverty Measures'),
          chapter('Food Security in India', 4, 'Food Security', 'Buffer Stock', 'Public Distribution System'),
          chapter('The French Revolution', 5, 'Causes of French Revolution', 'Events of 1789', 'Constitution and Republic', 'Impact'),
          chapter('Socialism in Europe and the Russian Revolution', 6, 'Ideas of Socialism', 'Russian Revolution 1917', 'Stalin\'s Russia'),
          chapter('Nazism and the Rise of Hitler', 7, 'Rise of Nazism', 'World War II', 'Holocaust', 'Youth in Nazi Germany'),
          chapter('Forest Society and Colonialism', 8, 'Colonial Forest Laws', 'Resistance Movements', 'Forest Societies'),
          chapter('Pastoralists in the Modern World', 9, 'Pastoral Nomads in Africa', 'Pastoralism in India', 'Colonial Impact'),
          chapter('India - Size and Location', 10, 'Location', 'Size', 'Standard Meridian'),
          chapter('Physical Features of India', 11, 'Himalayan Mountains', 'Northern Plains', 'Peninsular Plateau', 'Coastal Plains and Islands'),
          chapter('Drainage', 12, 'Drainage Systems', 'Himalayan and Peninsular Rivers', 'Lakes'),
          chapter('Climate', 13, 'Factors Affecting Climate', 'Monsoon', 'Seasons in India'),
          chapter('Natural Vegetation and Wildlife', 14, 'Types of Vegetation', 'Wildlife Sanctuaries'),
          chapter('What is Democracy? Why Democracy?', 15, 'Features of Democracy', 'Arguments For and Against Democracy'),
          chapter('Constitutional Design', 16, 'Drafting the Constitution', 'Fundamental Rights', 'Directive Principles'),
          chapter('Electoral Politics', 17, 'Election Process', 'Political Parties', 'Model Code of Conduct'),
          chapter('Working of Institutions', 18, 'Parliament', 'Executive', 'Judiciary'),
        ]),
        subject('English', [
          chapter('The Fun They Had', 1, 'Reading Comprehension', 'Grammar: Subject-Verb Agreement'),
          chapter('The Sound of Music', 2, 'Biographical Reading', 'Grammar: Tenses'),
          chapter('The Little Girl', 3, 'Story Analysis', 'Grammar: Adjectives and Adverbs'),
          chapter('A Truly Beautiful Mind', 4, 'Biography of Einstein', 'Grammar: Reported Speech'),
          chapter('The Snake and the Mirror', 5, 'Humour in Fiction', 'Grammar: Conditionals'),
          chapter('My Childhood', 6, 'Autobiography', 'Grammar: Passive Voice', 'Writing: Autobiographical Piece'),
          chapter('Packing', 7, 'Humorous Writing', 'Grammar: Gerunds and Infinitives'),
          chapter('Reach for the Top', 8, 'Inspirational Reading', 'Writing: Profile Writing'),
          chapter('The Bond of Love', 9, 'Animal Story', 'Grammar: Relative Clauses'),
          chapter('Kathmandu', 10, 'Travel Writing', 'Writing: Travel Diary'),
          chapter('If I Were You', 11, 'Drama Reading', 'Grammar: Modal Verbs'),
        ]),
      ],
    },
    {
      grade: '10',
      subjects: [
        subject('Mathematics', [
          chapter('Real Numbers', 1, 'Euclid\'s Division Lemma', 'Fundamental Theorem of Arithmetic', 'Irrational Numbers', 'Decimal Expansions'),
          chapter('Polynomials', 2, 'Geometrical Meaning of Zeroes', 'Relationship Between Zeroes and Coefficients', 'Division Algorithm for Polynomials'),
          chapter('Pair of Linear Equations in Two Variables', 3, 'Graphical Method', 'Substitution Method', 'Elimination Method', 'Cross-Multiplication Method'),
          chapter('Quadratic Equations', 4, 'Standard Form', 'Factorisation Method', 'Completing the Square', 'Quadratic Formula', 'Nature of Roots'),
          chapter('Arithmetic Progressions', 5, 'AP Definition and Terms', 'nth Term of AP', 'Sum of First n Terms'),
          chapter('Triangles', 6, 'Similar Triangles', 'Basic Proportionality Theorem', 'Criteria for Similarity: AA SAS SSS', 'Area of Similar Triangles', 'Pythagoras Theorem'),
          chapter('Coordinate Geometry', 7, 'Distance Formula', 'Section Formula', 'Area of Triangle'),
          chapter('Introduction to Trigonometry', 8, 'Trigonometric Ratios', 'Trigonometric Identities', 'Trigonometric Ratios of Complementary Angles'),
          chapter('Applications of Trigonometry', 9, 'Heights and Distances'),
          chapter('Circles', 10, 'Tangent to a Circle', 'Number of Tangents from External Point'),
          chapter('Constructions', 11, 'Division of Line Segment', 'Tangents to Circle'),
          chapter('Areas Related to Circles', 12, 'Circumference and Area', 'Area of Sector', 'Area of Segment'),
          chapter('Surface Areas and Volumes', 13, 'Combination of Solids', 'Conversion of Solids', 'Frustum of Cone'),
          chapter('Statistics', 14, 'Mean by Direct Assumed Deviation Step Deviation Method', 'Mode', 'Median', 'Cumulative Frequency Ogive'),
          chapter('Probability', 15, 'Classical Probability', 'Events and Their Types'),
        ]),
        subject('Science', [
          chapter('Chemical Reactions and Equations', 1, 'Chemical Equations', 'Types of Chemical Reactions', 'Oxidation and Reduction', 'Effects of Oxidation'),
          chapter('Acids Bases and Salts', 2, 'Indicators', 'Acids and Bases in Solution', 'pH Scale', 'Salts and Their Preparation', 'Chemicals from Common Salt'),
          chapter('Metals and Non-Metals', 3, 'Properties of Metals and Non-Metals', 'Reactivity Series', 'Extraction of Metals', 'Corrosion'),
          chapter('Carbon and Its Compounds', 4, 'Bonding in Carbon', 'Versatile Nature of Carbon', 'Important Carbon Compounds', 'Soaps and Detergents'),
          chapter('Periodic Classification of Elements', 5, 'Dobereiner\'s Triads', 'Mendeleev\'s Periodic Table', 'Modern Periodic Table', 'Periodic Trends'),
          chapter('Life Processes', 6, 'Nutrition', 'Respiration', 'Transportation', 'Excretion'),
          chapter('Control and Coordination', 7, 'Nervous System', 'Reflex Action', 'Human Brain', 'Hormones and Endocrine System', 'Plant Hormones'),
          chapter('How Do Organisms Reproduce?', 8, 'Asexual Reproduction', 'Sexual Reproduction in Plants', 'Reproduction in Human Beings', 'Reproductive Health'),
          chapter('Heredity and Evolution', 9, 'Heredity', 'Mendel\'s Experiments', 'Sex Determination', 'Evolution', 'Darwin\'s Theory'),
          chapter('Light: Reflection and Refraction', 10, 'Reflection by Spherical Mirrors', 'Mirror Formula', 'Refraction of Light', 'Lens Formula', 'Power of Lens'),
          chapter('Human Eye and Colourful World', 11, 'Human Eye', 'Power of Accommodation', 'Defects of Vision', 'Refraction through Prism', 'Scattering of Light'),
          chapter('Electricity', 12, 'Electric Current and Potential', 'Ohm\'s Law', 'Resistance in Series and Parallel', 'Heating Effect of Current'),
          chapter('Magnetic Effects of Electric Current', 13, 'Magnetic Field', 'Electromagnetic Induction', 'Electric Generator', 'Domestic Electric Circuits'),
          chapter('Sources of Energy', 14, 'Conventional Sources of Energy', 'Non-Conventional Sources', 'Environmental Consequences'),
          chapter('Our Environment', 15, 'Ecosystem', 'Food Chains and Webs', 'Ozone Depletion', 'Waste Management'),
          chapter('Sustainable Management of Natural Resources', 16, 'Conservation', 'Water Harvesting', 'Coal and Petroleum Conservation'),
        ]),
        subject('Social Science', [
          chapter('The Rise of Nationalism in Europe', 1, 'Nationalism and French Revolution', 'Romantic Imagination', 'Hunger Hardship and Popular Revolt', 'Unification of Germany and Italy'),
          chapter('Nationalism in India', 2, 'Non-Cooperation Movement', 'Civil Disobedience Movement', 'Sense of Collective Belonging'),
          chapter('The Making of a Global World', 3, 'Pre-Modern World', 'Colonialism and Global Trade', 'Interwar Economy', 'Bretton Woods Institutions'),
          chapter('The Age of Industrialisation', 4, 'Before Industrialisation', 'Hand Labour and Steam Power', 'Industrialisation in India'),
          chapter('Print Culture and the Modern World', 5, 'Print Revolution', 'Gutenberg Press', 'Print in Colonial India', 'Women and Print'),
          chapter('Resources and Development', 6, 'Types of Resources', 'Land Use', 'Land Degradation', 'Soil Conservation'),
          chapter('Forest and Wildlife Resources', 7, 'Flora and Fauna', 'Depletion of Resources', 'Conservation and Protection'),
          chapter('Water Resources', 8, 'Water Scarcity', 'Multi-Purpose River Projects', 'Rainwater Harvesting'),
          chapter('Agriculture', 9, 'Types of Farming', 'Cropping Pattern', 'Major Crops', 'Agricultural Reforms'),
          chapter('Minerals and Energy Resources', 10, 'Types of Minerals', 'Distribution of Minerals', 'Energy Resources'),
          chapter('Manufacturing Industries', 11, 'Importance of Manufacturing', 'Location Factors', 'Agro-Based and Mineral-Based Industries', 'Industrial Pollution'),
          chapter('Lifelines of National Economy', 12, 'Roadways Railways Waterways Airways', 'Communication', 'International Trade'),
          chapter('Power Sharing', 13, 'Why Power Sharing', 'Forms of Power Sharing'),
          chapter('Federalism', 14, 'What is Federalism', 'Indian Federalism', 'Decentralisation'),
          chapter('Democracy and Diversity', 15, 'Social Divisions in Democracy', 'Outcomes of Politics of Social Divisions'),
          chapter('Gender Religion and Caste', 16, 'Gender and Politics', 'Religion Communalism and Politics', 'Caste and Politics'),
          chapter('Political Parties', 17, 'Why Political Parties', 'Party Systems', 'National Parties in India', 'Challenges to Political Parties'),
          chapter('Outcomes of Democracy', 18, 'Economic Growth', 'Inequality Reduction', 'Dignity and Freedom of Citizens'),
          chapter('Development', 19, 'What Development Promises', 'National Development', 'Human Development Index'),
          chapter('Sectors of the Indian Economy', 20, 'Primary Secondary Tertiary Sectors', 'GDP', 'Organised and Unorganised Sector'),
          chapter('Money and Credit', 21, 'Money as Medium of Exchange', 'Formal Sector Credit', 'Self Help Groups'),
          chapter('Globalisation and the Indian Economy', 22, 'Production Across Countries', 'MNCs', 'Trade Barriers', 'WTO'),
          chapter('Consumer Rights', 23, 'Consumer Movement', 'Consumer Rights', 'COPRA'),
        ]),
        subject('English', [
          chapter('A Letter to God', 1, 'Reading Comprehension', 'Grammar: Tenses'),
          chapter('Nelson Mandela: Long Walk to Freedom', 2, 'Autobiography Extract', 'Grammar: Passive Voice'),
          chapter('Two Stories About Flying', 3, 'Fiction Reading', 'Grammar: Modals'),
          chapter('From the Diary of Anne Frank', 4, 'Diary Extract', 'Grammar: Reported Speech'),
          chapter('Glimpses of India', 5, 'Travel Writing', 'Grammar: Conditionals', 'Writing: Description'),
          chapter('Mijbil the Otter', 6, 'Animal Story', 'Grammar: Relative Clauses'),
          chapter('Madam Rides the Bus', 7, 'Story Analysis', 'Grammar: Participles'),
          chapter('The Sermon at Benares', 8, 'Philosophical Reading', 'Writing: Essay'),
          chapter('The Proposal', 9, 'Drama Reading', 'Grammar: Question Tags'),
          chapter('Dust of Snow', 10, 'Poetry: Nature', 'Grammar: Subject-Verb Agreement'),
          chapter('Fire and Ice', 11, 'Poetry: Symbol and Metaphor'),
          chapter('A Tiger in the Zoo', 12, 'Poetry: Animals and Freedom'),
        ]),
      ],
    },
  ],
}

// ─── AP SSC ───────────────────────────────────────────────────────────────────
const AP_SSC: BoardData = {
  board: 'AP_SSC',
  label: 'AP SSC (State Board)',
  grades: [
    {
      grade: '6',
      subjects: [
        subject('Mathematics', [
          chapter('Knowing Our Numbers', 1, 'Large Numbers and Place Value', 'Comparison of Large Numbers', 'Estimation and Rounding', 'Roman Numerals'),
          chapter('Whole Numbers', 2, 'Natural Numbers and Whole Numbers', 'Number Line', 'Properties: Closure Commutativity Associativity', 'Patterns in Whole Numbers'),
          chapter('Playing with Numbers', 3, 'Factors and Multiples', 'Prime and Composite Numbers', 'Tests of Divisibility', 'LCM and HCF'),
          chapter('Basic Geometrical Concepts', 4, 'Points Lines Rays Planes', 'Angles and Their Types', 'Triangles and Quadrilaterals', 'Circles'),
          chapter('Measures and Measurements', 5, 'Units of Measurement', 'Perimeter of Shapes', 'Area of Rectangle and Square'),
          chapter('Integers', 6, 'Negative Numbers', 'Integers on Number Line', 'Addition and Subtraction of Integers', 'Applications'),
          chapter('Fractions', 7, 'Types of Fractions', 'Equivalent Fractions', 'Comparing and Ordering', 'Addition and Subtraction', 'Multiplication and Division'),
          chapter('Decimal Numbers', 8, 'Place Value in Decimals', 'Comparing Decimals', 'Operations on Decimals'),
          chapter('Data Handling', 9, 'Collecting and Organising Data', 'Pictograph', 'Bar Graph', 'Mean'),
          chapter('Algebra', 10, 'Variables and Constants', 'Algebraic Expressions', 'Simple Equations'),
          chapter('Ratio and Proportion', 11, 'Concept of Ratio', 'Equivalent Ratios', 'Proportion', 'Unitary Method'),
        ]),
        subject('Physical Science', [
          chapter('Food: Where Does It Come From?', 1, 'Sources of Food', 'Plant Parts We Eat', 'Animal Products'),
          chapter('Components of Food', 2, 'Carbohydrates Proteins Fats', 'Vitamins and Minerals', 'Balanced Diet', 'Deficiency Diseases'),
          chapter('Sorting Materials into Groups', 3, 'Properties of Materials', 'Soluble and Insoluble Substances', 'Transparent Translucent Opaque'),
          chapter('Separation of Substances', 4, 'Methods of Separation', 'Practical Applications'),
          chapter('Changes Around Us', 5, 'Reversible and Irreversible Changes', 'Physical and Chemical Changes'),
          chapter('Motion and Measurement', 6, 'Standard Units', 'Measurement of Length', 'Types of Motion: Rectilinear Circular Periodic'),
          chapter('Light and Shadows', 7, 'Sources of Light', 'Transparent and Opaque Objects', 'Formation of Shadows', 'Pinhole Camera'),
          chapter('Electricity and Circuits', 8, 'Electric Cell', 'Simple Circuit', 'Conductors and Insulators', 'Safety'),
          chapter('Magnets', 9, 'Types of Magnets', 'Properties of Magnets', 'Uses of Magnets'),
          chapter('Water', 10, 'Sources and Uses', 'Water Cycle', 'Conservation of Water'),
          chapter('Air Around Us', 11, 'Composition of Air', 'Importance of Air', 'Wind and Weather'),
        ]),
        subject('Biology', [
          chapter('Getting to Know Plants', 1, 'Types of Plants', 'Parts of a Plant', 'Roots Stem Leaves Functions'),
          chapter('Body Movements', 2, 'Human Skeleton', 'Joints and Types', 'Movement in Animals'),
          chapter('The Living Organisms and Their Surroundings', 3, 'Habitat', 'Adaptations in Plants and Animals', 'Terrestrial and Aquatic Habitats'),
          chapter('Garbage In Garbage Out', 4, 'Types of Waste', 'Composting and Vermicomposting', 'Recycling'),
        ]),
        subject('Social Studies', [
          chapter('What is History?', 1, 'Meaning of History', 'Sources of History'),
          chapter('Ancient Civilisations', 2, 'Harappan Civilisation', 'Mesopotamia Egypt', 'Chinese Civilisation'),
          chapter('Vedic Civilisation', 3, 'Early Vedic Period', 'Later Vedic Period', 'Society and Economy'),
          chapter('Janapadas and Mahajanapadas', 4, 'Rise of Janapadas', 'Mahajanapadas', 'Magadha Empire'),
          chapter('The Earth and Its Movements', 5, 'Shape and Size of Earth', 'Rotation and Revolution', 'Day Night and Seasons'),
          chapter('Latitudes and Longitudes', 6, 'Latitudes', 'Longitudes', 'Time Zones', 'GPS'),
          chapter('Our State Andhra Pradesh', 7, 'Location and Boundaries', 'Physical Features', 'Districts'),
          chapter('Local Self Government', 8, 'Gram Panchayat', 'Municipal Bodies', 'Functions'),
          chapter('Food and Nutrition', 9, 'Types of Food', 'Nutrients', 'Food Habits'),
        ]),
        subject('English', [
          chapter('Paragraph Reading and Comprehension', 1, 'Reading Skills', 'Answering Questions'),
          chapter('Grammar: Nouns and Pronouns', 2, 'Types of Nouns', 'Pronouns and Their Types'),
          chapter('Grammar: Verbs and Tenses', 3, 'Simple Present Past Future', 'Continuous Tenses'),
          chapter('Grammar: Adjectives and Adverbs', 4, 'Types of Adjectives', 'Degrees of Comparison', 'Types of Adverbs'),
          chapter('Writing Skills', 5, 'Paragraph Writing', 'Informal Letter Writing'),
          chapter('Vocabulary Building', 6, 'Synonyms and Antonyms', 'Word Meanings in Context'),
        ]),
        subject('Telugu', [
          chapter('వచనం', 1, 'వచన పఠనం', 'అర్థ గ్రహణం', 'ప్రశ్నలకు జవాబులు'),
          chapter('పద్యం', 2, 'పద్య పఠనం', 'భావం', 'వ్యాకరణం'),
          chapter('వ్యాకరణం - నామవాచకం', 3, 'నామవాచకాల రకాలు', 'లింగ వచనాలు'),
          chapter('వ్యాకరణం - క్రియ', 4, 'క్రియల రకాలు', 'కాలాలు'),
          chapter('రచన - వ్యాసం', 5, 'వ్యాస రచన', 'లేఖ రచన'),
        ]),
      ],
    },
    {
      grade: '7',
      subjects: [
        subject('Mathematics', [
          chapter('Integers', 1, 'Multiplication of Integers', 'Division of Integers', 'Properties of Integers'),
          chapter('Fractions and Decimals', 2, 'Multiplication of Fractions', 'Division of Fractions', 'Operations on Decimals'),
          chapter('Simple Equations', 3, 'Setting Up Equations', 'Solving Equations', 'Applications'),
          chapter('Lines and Angles', 4, 'Pairs of Angles', 'Transversal and Parallel Lines', 'Angle Sum Properties'),
          chapter('Triangle and Its Properties', 5, 'Medians and Altitudes', 'Exterior Angle Property', 'Angle Sum Property', 'Pythagoras Theorem'),
          chapter('Congruence of Triangles', 6, 'Congruent Figures', 'SSS SAS AAS RHS Congruence'),
          chapter('Ratio and Proportion', 7, 'Ratio', 'Proportion', 'Unitary Method', 'Percentage'),
          chapter('Data Handling', 8, 'Mean Median Mode', 'Bar Graphs', 'Probability'),
          chapter('Perimeter and Area', 9, 'Area of Parallelogram', 'Area of Triangle', 'Circle: Circumference and Area'),
          chapter('Algebraic Expressions', 10, 'Terms and Factors', 'Addition Subtraction of Expressions', 'Multiplication'),
          chapter('Exponents and Powers', 11, 'Exponents', 'Laws of Exponents', 'Standard Form'),
          chapter('Symmetry', 12, 'Line Symmetry', 'Rotational Symmetry'),
        ]),
        subject('Physical Science', [
          chapter('Heat', 1, 'Temperature and Thermometers', 'Types of Heat Transfer', 'Conductors and Insulators of Heat'),
          chapter('Acids Bases and Salts', 2, 'Properties of Acids and Bases', 'Indicators', 'Neutralisation', 'Uses'),
          chapter('Physical and Chemical Changes', 3, 'Physical Changes', 'Chemical Changes', 'Difference Between Them'),
          chapter('Winds Storms and Cyclones', 4, 'Air Movement', 'Cyclone Formation', 'Safety Measures'),
          chapter('Motion and Time', 5, 'Speed', 'Distance-Time Graphs', 'Units of Speed'),
          chapter('Electric Current and Effects', 6, 'Circuit Diagrams', 'Heating Effect', 'Magnetic Effect', 'Electromagnets'),
          chapter('Light', 7, 'Laws of Reflection', 'Mirrors: Plane Concave Convex', 'Lenses', 'Dispersion of Light'),
        ]),
        subject('Biology', [
          chapter('Nutrition in Plants', 1, 'Photosynthesis', 'Parasitic and Saprophytic Nutrition', 'Insectivorous Plants'),
          chapter('Nutrition in Animals', 2, 'Digestion in Humans', 'Nutrition in Amoeba and Paramecium'),
          chapter('Fibre to Fabric', 3, 'Types of Fibres: Wool and Silk', 'Silk Worm Life Cycle', 'Processing of Fibres'),
          chapter('Respiration in Organisms', 4, 'Aerobic and Anaerobic Respiration', 'Breathing in Different Animals', 'Respiration in Plants'),
          chapter('Reproduction in Plants', 5, 'Asexual Reproduction', 'Sexual Reproduction in Flowering Plants', 'Seed Dispersal'),
          chapter('Transportation in Plants and Animals', 6, 'Water Transport in Plants', 'Circulatory System', 'Excretion'),
          chapter('Weather Climate and Adaptations', 7, 'Climate Zones', 'Animal and Plant Adaptations', 'Migration'),
          chapter('Soil', 8, 'Soil Profile', 'Types of Soil', 'Soil and Crops'),
          chapter('Forests: Our Lifeline', 9, 'Components of Forest', 'Importance of Forests', 'Conservation'),
          chapter('Wastewater Story', 10, 'Sewage Treatment', 'Sanitation Practices', 'Diseases'),
        ]),
        subject('Social Studies', [
          chapter('Medieval Period in India', 1, 'Delhi Sultanate', 'Mughal Empire', 'Regional Kingdoms'),
          chapter('Socio-Religious Reform Movements', 2, 'Bhakti Movement', 'Sufi Movement'),
          chapter('Society in Medieval India', 3, 'Social Structure', 'Position of Women', 'Caste System'),
          chapter('Interior of the Earth', 4, 'Layers of Earth', 'Earthquakes', 'Volcanoes'),
          chapter('Atmosphere and Weather', 5, 'Composition of Atmosphere', 'Layers', 'Weather and Climate'),
          chapter('Water', 6, 'Freshwater and Saltwater', 'Ocean Movements', 'Water Cycle'),
          chapter('Our State AP - Natural Resources', 7, 'Land Resources', 'Water Resources', 'Forest Resources', 'Minerals'),
          chapter('Food Security', 8, 'Food Security Meaning', 'Buffer Stock', 'PDS System'),
          chapter('Production and Livelihood', 9, 'Farming Methods', 'Non-Farm Activities', 'Labourers'),
          chapter('Market and Consumer', 10, 'Types of Markets', 'Consumer Awareness', 'Consumer Rights'),
        ]),
        subject('English', [
          chapter('Reading Comprehension - Factual', 1, 'Factual Passages', 'Note-Taking'),
          chapter('Reading Comprehension - Literary', 2, 'Stories and Poems', 'Inference Skills'),
          chapter('Grammar: Tenses', 3, 'Present Perfect', 'Past Perfect', 'Future Perfect'),
          chapter('Grammar: Voice - Active and Passive', 4, 'Active Voice', 'Passive Voice', 'Transformations'),
          chapter('Writing: Formal Letter', 5, 'Formal Letter Format', 'Letter to Editor', 'Letter to Authority'),
          chapter('Writing: Report Writing', 6, 'News Report', 'Report Format'),
          chapter('Vocabulary', 7, 'Phrasal Verbs', 'Idioms', 'Word Formation'),
        ]),
        subject('Telugu', [
          chapter('వచన పాఠాలు', 1, 'పఠనం', 'అర్థ గ్రహణం', 'సారాంశం'),
          chapter('పద్య పాఠాలు', 2, 'పద్య పఠనం', 'భావ వివరణ', 'అర్థాలు'),
          chapter('వ్యాకరణం - సంధులు', 3, 'సంధి రకాలు', 'ఉదాహరణలు'),
          chapter('వ్యాకరణం - సమాసాలు', 4, 'సమాస రకాలు', 'విగ్రహ వాక్యాలు'),
          chapter('రచన నైపుణ్యాలు', 5, 'వ్యాస రచన', 'కథ రచన', 'అభినందన పత్రం'),
        ]),
      ],
    },
    {
      grade: '8',
      subjects: [
        subject('Mathematics', [
          chapter('Rational Numbers', 1, 'Properties of Rational Numbers', 'Rational Numbers on Number Line', 'Operations on Rational Numbers'),
          chapter('Linear Equations in One Variable', 2, 'Simple Equations', 'Applications', 'Equations with Variables on Both Sides'),
          chapter('Construction of Quadrilaterals', 3, 'Constructing Quadrilaterals', 'Special Quadrilaterals'),
          chapter('Exponents and Powers', 4, 'Negative Exponents', 'Scientific Notation', 'Laws of Exponents'),
          chapter('Comparing Quantities using Proportion', 5, 'Ratios and Percentages', 'Profit Loss Discount', 'Simple and Compound Interest'),
          chapter('Square Roots and Cube Roots', 6, 'Perfect Squares', 'Finding Square Roots', 'Perfect Cubes', 'Cube Roots'),
          chapter('Frequency Distribution Tables and Graphs', 7, 'Frequency Distribution', 'Histograms', 'Frequency Polygons', 'Pie Charts'),
          chapter('Area of Plane Figures', 8, 'Area of Trapezium', 'Area of Quadrilaterals', 'Area of Circles'),
          chapter('Direct and Inverse Proportions', 9, 'Direct Proportion', 'Inverse Proportion', 'Time and Work'),
          chapter('Algebraic Expressions, Identities and Factorisation', 10, 'Expressions and Identities', 'Standard Identities', 'Factorisation Methods'),
          chapter('Visualising 3D in 2D', 11, 'Views of Solid Shapes', 'Euler\'s Formula', 'Nets of Solids'),
          chapter('Introduction to Graphs', 12, 'Bar Graph Pie Chart Histogram', 'Linear Graphs', 'Applications of Graphs'),
          chapter('Mensuration', 13, 'Surface Area of Cylinder Cone Sphere', 'Volume of Cylinder Cone Sphere'),
        ]),
        subject('Physical Science', [
          chapter('Matter and Its States', 1, 'States of Matter', 'Change of State', 'Evaporation', 'Sublimation'),
          chapter('Synthetic Fibres and Plastics', 2, 'Synthetic Fibres', 'Types of Plastics', 'Biodegradable vs Non-biodegradable'),
          chapter('Metals and Non-Metals', 3, 'Properties of Metals', 'Properties of Non-Metals', 'Chemical Properties'),
          chapter('Coal and Petroleum', 4, 'Fossil Fuels', 'Processing of Coal', 'Petroleum Refining', 'Natural Gas'),
          chapter('Combustion and Flame', 5, 'Conditions for Combustion', 'Types of Combustion', 'Flame Structure', 'Fire Extinguishers'),
          chapter('Force and Pressure', 6, 'Force and Its Effects', 'Types of Forces', 'Pressure Formula', 'Atmospheric Pressure', 'Bernoulli\'s Principle'),
          chapter('Friction', 7, 'Types of Friction', 'Factors Affecting Friction', 'Advantages and Disadvantages', 'Reducing Friction'),
          chapter('Sound', 8, 'Propagation of Sound', 'Characteristics', 'Speed of Sound', 'Reflection of Sound', 'Noise Pollution'),
          chapter('Some Natural Phenomena', 9, 'Earthquakes', 'Lightning', 'Safety Measures'),
          chapter('Chemical Effects of Electric Current', 10, 'Electrolysis', 'Electroplating', 'Applications'),
          chapter('Stars and Solar System', 11, 'Stars', 'Constellations', 'Solar System Planets', 'Moon', 'Comets'),
        ]),
        subject('Biology', [
          chapter('Cell Structure and Functions', 1, 'Cell Theory', 'Prokaryotic and Eukaryotic Cells', 'Organelles Functions', 'Cell Division'),
          chapter('Micro-organisms', 2, 'Types of Microorganisms', 'Useful Microorganisms', 'Diseases Caused by Microorganisms', 'Preservation of Food'),
          chapter('Conservation of Plants and Animals', 3, 'Deforestation Effects', 'Wildlife Sanctuaries', 'National Parks', 'Biosphere Reserves'),
          chapter('Reproduction in Animals', 4, 'Asexual Reproduction', 'Sexual Reproduction', 'Internal and External Fertilisation', 'Development'),
          chapter('Reaching the Age of Adolescence', 5, 'Changes at Puberty', 'Endocrine Glands and Hormones', 'Reproductive Health'),
          chapter('Crop Production and Management', 6, 'Crop Seasons', 'Irrigation Methods', 'Fertilisers and Manures', 'Storage'),
          chapter('Pollution of Air and Water', 7, 'Air Pollutants', 'Water Pollutants', 'Effects and Prevention'),
        ]),
        subject('Social Studies', [
          chapter('Agriculture in India', 1, 'Types of Farming', 'Rabi and Kharif Crops', 'Green Revolution', 'Problems of Farmers'),
          chapter('Industries in India', 2, 'Classification of Industries', 'Iron and Steel Industry', 'Cotton Textile Industry', 'Special Economic Zones'),
          chapter('Transport and Communication', 3, 'Road Rail Water Air Transport', 'Communication Systems', 'Importance'),
          chapter('Understanding Secularism', 4, 'Secularism in India', 'Religious Freedom', 'Government and Religion'),
          chapter('Social Justice', 5, 'Issues of Equality', 'Discrimination', 'Constitutional Provisions'),
          chapter('Confronting Marginalisation', 6, 'Marginalised Groups', 'Adivasis Dalits Muslims Women', 'Constitutional Safeguards'),
          chapter('Law and Social Justice', 7, 'Minimum Wage Act', 'Environmental Laws', 'Role of Government'),
          chapter('Physical Features of India', 8, 'Himalayan Mountains', 'Northern Plains', 'Deccan Plateau', 'Coastal Areas'),
          chapter('Climate of India', 9, 'Monsoon', 'Seasons', 'Regional Variations'),
          chapter('Our State AP: Government', 10, 'AP State Formation', 'Government Structure', 'Districts and Mandals'),
        ]),
        subject('English', [
          chapter('Reading: Prose and Poetry', 1, 'Reading for Main Idea', 'Inference and Interpretation'),
          chapter('Grammar: Conditionals', 2, 'Zero First Second Third Conditional'),
          chapter('Grammar: Reported Speech', 3, 'Direct and Indirect Speech', 'Commands Questions Statements'),
          chapter('Writing: Essay', 4, 'Argumentative Essay', 'Descriptive Essay', 'Narrative Essay'),
          chapter('Writing: Email and Notice', 5, 'Formal Email Format', 'Notice Writing Format'),
          chapter('Vocabulary and Phrases', 6, 'Collocations', 'Fixed Expressions', 'Connotations'),
        ]),
        subject('Telugu', [
          chapter('వచన పాఠాలు', 1, 'గద్య పఠనం', 'భావ వివరణ', 'సారాంశం రచన'),
          chapter('పద్య పాఠాలు', 2, 'పద్య పఠనం', 'ఛందస్సు పరిచయం', 'అర్థాలు భావాలు'),
          chapter('వ్యాకరణం - ఆర్య సమాసాలు', 3, 'తత్పురుష', 'కర్మధారయ', 'బహువ్రీహి', 'ద్వంద్వ'),
          chapter('వ్యాకరణం - వాక్య రూపాంతరాలు', 4, 'ప్రత్యక్ష పరోక్ష కథనాలు', 'వాక్య రీతులు'),
          chapter('రచన నైపుణ్యాలు', 5, 'వ్యాసం', 'ప్రసంగం', 'నివేదిక రచన'),
        ]),
      ],
    },
    {
      grade: '9',
      subjects: [
        subject('Mathematics', [
          chapter('Real Numbers', 1, 'Rational and Irrational Numbers', 'Real Number Line', 'Surds', 'Laws of Exponents'),
          chapter('Polynomials and Factorisation', 2, 'Degree of Polynomial', 'Zeroes of Polynomial', 'Factor and Remainder Theorem', 'Factorisation Methods'),
          chapter('The Elements of Geometry', 3, 'Euclid\'s Elements', 'Axioms and Postulates', 'Theorems'),
          chapter('Lines and Angles', 4, 'Types of Angles', 'Parallel Lines and Transversal', 'Angle Sum Properties'),
          chapter('Co-ordinate Geometry', 5, 'Cartesian Plane', 'Plotting Points', 'Graph of Linear Equations'),
          chapter('Linear Equations in Two Variables', 6, 'Solutions of Linear Equations', 'Graphical Representation', 'Applications'),
          chapter('Triangles', 7, 'Congruence of Triangles', 'Inequalities in a Triangle', 'Similarity Basics'),
          chapter('Quadrilaterals', 8, 'Properties of Quadrilaterals', 'Midpoint Theorem', 'Special Quadrilaterals'),
          chapter('Statistics', 9, 'Mean Median Mode', 'Frequency Distribution', 'Histograms', 'Cumulative Frequency'),
          chapter('Surface Areas and Volumes', 10, 'Prisms and Cylinders', 'Cones and Spheres', 'Combinations of Solids'),
          chapter('Areas', 11, 'Area of Triangle', 'Heron\'s Formula', 'Quadrilaterals'),
          chapter('Circles', 12, 'Chord Properties', 'Tangent to Circle', 'Cyclic Quadrilateral'),
          chapter('Geometrical Constructions', 13, 'Constructing Triangles', 'Constructing Quadrilaterals'),
          chapter('Probability', 14, 'Outcomes and Events', 'Probability Formula', 'Complementary Events'),
          chapter('Mathematical Modelling', 15, 'Concept of Mathematical Modelling', 'Applications'),
        ]),
        subject('Physical Science', [
          chapter('Matter Around Us', 1, 'States of Matter', 'Interconversion of States', 'Plasma and BEC'),
          chapter('Chemical Substances - Nature and Behaviour', 2, 'Mixtures and Solutions', 'Acids Bases Salts', 'pH Scale'),
          chapter('Structure of the Atom', 3, 'Electrons Protons Neutrons', 'Atomic Models', 'Valence Electrons', 'Atomic Number and Mass Number'),
          chapter('Motion', 4, 'Distance and Displacement', 'Speed Velocity Acceleration', 'Equations of Motion', 'Graphs'),
          chapter('Laws of Motion', 5, 'Newton\'s Three Laws', 'Inertia', 'Momentum', 'Action and Reaction'),
          chapter('Gravitation', 6, 'Universal Gravitation', 'Free Fall', 'Weight and Mass', 'Archimedes\' Principle'),
          chapter('Floating Bodies', 7, 'Buoyancy', 'Density and Relative Density', 'Applications'),
          chapter('Work and Energy', 8, 'Work', 'Energy Types', 'Conservation of Energy', 'Power'),
          chapter('Sound', 9, 'Wave Properties', 'Speed of Sound', 'Reflection and Echo', 'Ultrasound', 'SONAR'),
          chapter('Electricity', 10, 'Electric Charge and Field', 'Potential Difference', 'Ohm\'s Law', 'Resistors'),
          chapter('Electromagnetism', 11, 'Magnetic Field of Current', 'Electromagnetic Induction', 'AC and DC'),
        ]),
        subject('Biology', [
          chapter('Cell - Its Structure and Functions', 1, 'Cell Organisation', 'Prokaryotes and Eukaryotes', 'Organelle Functions'),
          chapter('Animal Tissues', 2, 'Epithelial Tissue', 'Connective Tissue', 'Muscle Tissue', 'Nervous Tissue'),
          chapter('Diversity in Living Organisms', 3, 'Classification of Living Things', 'Five Kingdom Classification', 'Plant and Animal Kingdoms'),
          chapter('Nutrition', 4, 'Autotrophic Nutrition', 'Heterotrophic Nutrition', 'Human Digestive System'),
          chapter('Respiration', 5, 'Aerobic and Anaerobic Respiration', 'Human Respiratory System', 'Exchange of Gases'),
          chapter('Excretion', 6, 'Metabolic Wastes', 'Excretory System in Humans', 'Kidney Function'),
          chapter('Transportation', 7, 'Blood and Its Composition', 'Circulatory System', 'Transport in Plants'),
          chapter('Nervous System', 8, 'Neurons', 'Human Brain and Spinal Cord', 'Reflex Arc', 'Sense Organs'),
          chapter('Reproduction', 9, 'Asexual Reproduction', 'Sexual Reproduction in Plants', 'Human Reproductive System'),
          chapter('Heredity', 10, 'Heredity and Variation', 'Mendel\'s Laws', 'Sex Determination'),
          chapter('Our Environment', 11, 'Ecosystem Components', 'Food Chains and Webs', 'Biodiversity', 'Conservation'),
          chapter('Natural Resources', 12, 'Renewable Resources', 'Non-Renewable Resources', 'Conservation Practices'),
        ]),
        subject('Social Studies', [
          chapter('The Harappan Civilisation', 1, 'Discovery', 'Town Planning', 'Trade and Culture'),
          chapter('The Vedic Civilisation', 2, 'Rig Vedic Period', 'Later Vedic Period', 'Society and Religion'),
          chapter('Jainism and Buddhism', 3, 'Causes of Reform', 'Teachings', 'Impact on Society'),
          chapter('The Mauryan Empire', 4, 'Chandragupta Maurya', 'Ashoka\'s Rule and Dhamma', 'Administration'),
          chapter('Deccan and South India', 5, 'Satavahanas', 'Ikshvakus', 'Pallavas and Chalukyas'),
          chapter('Indian Geography - Physical Features', 6, 'Himalayan Region', 'Peninsular Plateau', 'River Systems'),
          chapter('Indian Geography - Climate', 7, 'Monsoon Mechanism', 'Seasons', 'Climate Zones in India'),
          chapter('Social Organisation', 8, 'Family Types', 'Community and Society', 'Social Groups'),
          chapter('Andhra Pradesh - Our State', 9, 'Formation of AP', 'Physical and Political Features', 'Economy'),
          chapter('Food and Nutrition', 10, 'Types of Nutrients', 'Balanced Diet', 'Malnutrition'),
          chapter('Livelihood and Occupation', 11, 'Types of Occupations', 'Challenges', 'Government Schemes'),
        ]),
        subject('English', [
          chapter('Reading Skills', 1, 'Skimming and Scanning', 'Critical Reading', 'Making Inferences'),
          chapter('Grammar: Complex Sentences', 2, 'Noun Clauses', 'Adjective Clauses', 'Adverb Clauses'),
          chapter('Grammar: Transformation', 3, 'Degrees of Comparison', 'Voice Change', 'Narration Change'),
          chapter('Writing: Formal Writing', 4, 'Formal Letter', 'Report Writing', 'Official Notice'),
          chapter('Writing: Creative Writing', 5, 'Short Story', 'Descriptive Piece', 'Personal Narrative'),
          chapter('Literature Appreciation', 6, 'Prose Analysis', 'Poetry Analysis', 'Drama Elements'),
        ]),
        subject('Telugu', [
          chapter('వచన పాఠాలు', 1, 'ఆధునిక గద్యం', 'విమర్శనాత్మక పఠనం', 'సారాంశం'),
          chapter('పద్య పాఠాలు', 2, 'క్లాసికల్ పద్యాలు', 'ఆధునిక కవిత్వం', 'అర్థ వివరణ'),
          chapter('వ్యాకరణం - వాక్య నిర్మాణం', 3, 'వాక్య రకాలు', 'సమాస వాక్యాలు', 'సంక్లిష్ట వాక్యాలు'),
          chapter('వ్యాకరణం - ఛందస్సు', 4, 'వృత్తాలు', 'జాతి ఛందాలు', 'మాత్రా ఛందాలు'),
          chapter('రచన నైపుణ్యాలు', 5, 'వ్యాసం', 'వాక్య సంకలన వ్యాసం', 'అభ్యంతర వ్యాసం'),
        ]),
      ],
    },
    {
      grade: '10',
      subjects: [
        subject('Mathematics', [
          chapter('Real Numbers', 1, 'Euclid\'s Division Lemma', 'Fundamental Theorem of Arithmetic', 'Rational and Irrational Numbers', 'Decimal Expansions'),
          chapter('Sets', 2, 'Types of Sets', 'Set Operations', 'Venn Diagrams'),
          chapter('Polynomials', 3, 'Zeroes of Polynomials', 'Relationship Between Zeroes and Coefficients', 'Division Algorithm'),
          chapter('Pair of Linear Equations in Two Variables', 4, 'Graphical Method', 'Algebraic Methods', 'Word Problems'),
          chapter('Quadratic Equations', 5, 'Methods of Solving', 'Nature of Roots', 'Applications'),
          chapter('Progressions', 6, 'Arithmetic Progression', 'nth Term and Sum', 'Geometric Progression'),
          chapter('Coordinate Geometry', 7, 'Distance Formula', 'Section Formula', 'Area of Triangle', 'Slope'),
          chapter('Similar Triangles', 8, 'Similarity Criteria', 'Basic Proportionality Theorem', 'Areas of Similar Triangles', 'Pythagoras Theorem'),
          chapter('Tangents and Secants to a Circle', 9, 'Tangent from External Point', 'Lengths of Tangents', 'Angle in Semicircle'),
          chapter('Mensuration', 10, 'Surface Areas of Combinations', 'Volumes of Combinations', 'Frustum of Cone'),
          chapter('Trigonometry', 11, 'Trigonometric Ratios', 'Identities', 'Heights and Distances'),
          chapter('Applications of Trigonometry', 12, 'Angles of Elevation and Depression', 'Practical Problems'),
          chapter('Probability', 13, 'Classical Probability', 'Addition Theorem', 'Conditional Probability Basics'),
          chapter('Statistics', 14, 'Mean by Different Methods', 'Median Mode', 'Ogive Curves'),
        ]),
        subject('Physical Science', [
          chapter('Chemical Reactions and Equations', 1, 'Balancing Chemical Equations', 'Types of Chemical Reactions', 'Oxidation Reduction'),
          chapter('Acids Bases and Salts', 2, 'Strength of Acids and Bases', 'pH Scale', 'Salts', 'Common Chemicals'),
          chapter('Metals and Non-Metals', 3, 'Reactivity Series', 'Extraction of Metals', 'Alloys', 'Corrosion Prevention'),
          chapter('Carbon and Its Compounds', 4, 'Covalent Bonding', 'Organic Compounds', 'Functional Groups', 'Soaps and Detergents'),
          chapter('Classification of Elements', 5, 'Early Classification', 'Mendeleev\'s Table', 'Modern Periodic Table', 'Periodic Properties'),
          chapter('Reflection of Light by Different Surfaces', 6, 'Laws of Reflection', 'Plane Mirror', 'Spherical Mirrors', 'Mirror Formula'),
          chapter('Refraction of Light at Plane Surfaces', 7, 'Laws of Refraction', 'Total Internal Reflection', 'Snell\'s Law'),
          chapter('Refraction of Light at Curved Surfaces', 8, 'Convex and Concave Lenses', 'Lens Formula', 'Power of Lens'),
          chapter('Human Eye and Colourful World', 9, 'Structure of Eye', 'Defects of Vision', 'Dispersion', 'Scattering of Light'),
          chapter('Electric Current', 10, 'Ohm\'s Law', 'Resistance', 'Resistors in Series and Parallel', 'Electric Power'),
          chapter('Magnetic Effects of Electric Current', 11, 'Magnetic Field and Force', 'Electromagnetic Induction', 'Electric Generator'),
          chapter('Principles of Metallurgy', 12, 'Minerals and Ores', 'Extraction Process', 'Thermite Process', 'Refining'),
        ]),
        subject('Biology', [
          chapter('Nutrition', 1, 'Types of Nutrition', 'Photosynthesis Detailed', 'Respiration in Detail', 'Animal Nutrition'),
          chapter('Respiration', 2, 'Cellular Respiration', 'Glycolysis Krebs Cycle', 'Respiratory Organs in Animals'),
          chapter('Transportation', 3, 'Blood Groups', 'Heart and Circulation', 'Lymphatic System', 'Transport in Plants'),
          chapter('Excretion', 4, 'Nitrogenous Wastes', 'Kidney and Nephron', 'Dialysis', 'Excretion in Plants'),
          chapter('Control and Coordination', 5, 'Nervous System', 'Endocrine System', 'Hormones and Diseases', 'Plant Hormones'),
          chapter('Reproduction', 6, 'Asexual Methods', 'Sexual Reproduction in Plants', 'Human Reproduction', 'Reproductive Health'),
          chapter('Coordination in Life Processes', 7, 'Homeostasis', 'Feedback Mechanisms'),
          chapter('Heredity', 8, 'Mendel\'s Experiments', 'Laws of Heredity', 'Chromosomes and Genes', 'Sex Determination'),
          chapter('Evolution', 9, 'Evidences of Evolution', 'Darwin\'s Theory', 'Human Evolution'),
          chapter('Our Environment', 10, 'Biotic and Abiotic Components', 'Food Chains Webs Pyramids', 'Ecosystem Services'),
          chapter('Natural Resources', 11, 'Air Water Soil Resources', 'Biodiversity', 'Conservation Methods', 'Sustainability'),
        ]),
        subject('Social Studies', [
          chapter('Development Concept', 1, 'Meaning of Development', 'National Development', 'Comparison Between Countries'),
          chapter('Sectors of Economy', 2, 'Primary Secondary Tertiary', 'GDP', 'Organised Unorganised Sector'),
          chapter('Money and Credit', 3, 'Modern Forms of Money', 'Formal and Informal Credit', 'Self-Help Groups'),
          chapter('Globalisation', 4, 'MNCs', 'Trade and Investment', 'WTO', 'Impact of Globalisation'),
          chapter('Consumer Rights', 5, 'Consumer Movement', 'Rights of Consumers', 'COPRA and Redressal'),
          chapter('Forest Society and Colonialism', 6, 'Colonial Forest Laws', 'Resistance Movements'),
          chapter('Pastoralists in the Modern World', 7, 'Pastoral Communities', 'Impact of Colonialism'),
          chapter('India - Physical Features', 8, 'Relief Features', 'River Systems', 'Coastal Plains'),
          chapter('India - Climate', 9, 'Monsoon and Seasons', 'Distribution of Rainfall', 'Climate and Human Life'),
          chapter('India - Resources and Development', 10, 'Land and Soil Resources', 'Water Resources', 'Mineral Resources', 'Energy Resources'),
          chapter('Nationalism in India', 11, 'Colonial Economy', 'Non-Cooperation Movement', 'Civil Disobedience', 'Quit India'),
          chapter('The Nationalist Movement in AP', 12, 'Andhra Mahasabha', 'Role of AP in Freedom Struggle', 'Important Leaders'),
          chapter('Democracy and Diversity', 13, 'Social Divisions', 'Gender Religion Caste', 'Political Representation'),
          chapter('Political Parties', 14, 'Functions of Political Parties', 'National Parties', 'Challenges to Parties'),
          chapter('Outcomes of Democracy', 15, 'Expectations from Democracy', 'Democratic Accountability', 'Citizen Participation'),
        ]),
        subject('English', [
          chapter('Reading: Long Passages', 1, 'Extended Comprehension', 'Critical Analysis', 'Summary Writing'),
          chapter('Grammar: Advanced', 2, 'Inversion', 'Cleft Sentences', 'Ellipsis', 'Substitution'),
          chapter('Grammar: Mixed Revision', 3, 'Transformation Exercises', 'Error Correction', 'Sentence Completion'),
          chapter('Writing: Formal Documents', 4, 'Application Letter', 'Curriculum Vitae', 'Official Report'),
          chapter('Writing: Creative and Discursive', 5, 'Argumentative Essay', 'Speech Writing', 'Creative Story'),
          chapter('Literature: Poetry and Drama', 6, 'Poetry Analysis', 'Drama Analysis', 'Literary Devices'),
        ]),
        subject('Telugu', [
          chapter('వచన పాఠాలు', 1, 'వివిధ వచన ప్రక్రియలు', 'విమర్శనాత్మక విశ్లేషణ'),
          chapter('పద్య పాఠాలు', 2, 'ప్రాచీన పద్యాలు', 'ఆధునిక కవిత్వం', 'ఛందో విశ్లేషణ'),
          chapter('వ్యాకరణం - సమగ్ర అభ్యాసం', 3, 'సంధులు సమాసాలు', 'వాక్య రూపాంతరాలు', 'ప్రత్యయాలు'),
          chapter('వ్యాకరణం - అలంకారాలు', 4, 'శబ్దాలంకారాలు', 'అర్థాలంకారాలు'),
          chapter('రచన నైపుణ్యాలు - పరీక్ష సన్నద్ధత', 5, 'వ్యాస రచన', 'లేఖ రచన', 'కవితా రచన'),
        ]),
      ],
    },
  ],
}

// ─── TS SSC (Telangana) — mirrors AP SSC structure with TS-specific tweaks ──
const TS_SSC: BoardData = {
  board: 'TS_SSC',
  label: 'TS SSC (Telangana Board)',
  grades: AP_SSC.grades.map(g => ({
    ...g,
    subjects: g.subjects.map(s => ({
      ...s,
      subject: s.subject === 'Telugu' ? 'Telugu' : s.subject,
    })),
  })),
}

export const ALL_BOARDS: BoardData[] = [CBSE, AP_SSC, TS_SSC]

export function getBoardData(board: string): BoardData | undefined {
  return ALL_BOARDS.find(b => b.board === board)
}

export function getGradeData(board: string, grade: string): GradeEntry | undefined {
  return getBoardData(board)?.grades.find(g => g.grade === grade)
}

export function getBoardLabels(): { value: string; label: string }[] {
  return ALL_BOARDS.map(b => ({ value: b.board, label: b.label }))
}
