'use client'

import { useCallback, useEffect, useState } from 'react'
import { GRADE_SEQUENCE } from '@/lib/grades'
import type { ReportData } from './types'
import { useFeeStore } from '@/lib/stores/feeStore'
import { LoadErrorBanner } from './LoadErrorBanner'

const GRADES = GRADE_SEQUENCE
function gradeLabel(g: string): string { return /^\d+$/.test(g) ? `Grade ${g}` : g }

function fmt(n: number | string) {
  return `₹${Number(n).toLocaleString('en-IN')}`
}
function pct(num: number, den: number) {
  if (!den || den < 0) return 0
  return Math.min(100, Math.round((num / den) * 100))
}

// ─── Fee Audit Report → print-HTML (used for "Save as PDF") ────────────────────
const RUPEE = (n: number) => `₹${Number(n || 0).toLocaleString('en-IN')}`
function buildAuditPdfHtml(rep: Record<string, unknown>): string {
  const meta = rep.meta as { school_name: string; academic_year: string; generated_by: string; generated_on: string; scope?: string }
  const head = `
    <div class="hdr">
      <div class="title">${rep.kind === 'student' ? 'Individual Student Fee Report' : 'Fee Audit Report'}</div>
      <div class="sub">${meta.school_name} · ${meta.academic_year}${meta.scope ? ' · ' + meta.scope : ''}</div>
      <div class="meta">Generated by ${meta.generated_by} on ${new Date(meta.generated_on).toLocaleString('en-IN')}</div>
    </div>`
  const style = `<style>
    body{font-family:Arial,sans-serif;padding:28px;color:#222;max-width:980px;margin:0 auto;font-size:12px}
    .hdr{text-align:center;border-bottom:2px solid #333;padding-bottom:12px;margin-bottom:16px}
    .title{font-size:20px;font-weight:bold}.sub{font-size:13px;color:#555;margin-top:4px}.meta{font-size:11px;color:#888;margin-top:3px}
    h3{font-size:13px;margin:18px 0 6px;border-left:3px solid #1e3a5f;padding-left:8px}
    table{width:100%;border-collapse:collapse;margin-bottom:10px}
    th{background:#1e3a5f;color:#fff;padding:6px 8px;text-align:left;font-size:11px;border:1px solid #1e3a5f}
    td{padding:5px 8px;font-size:11px;border:1px solid #ddd}
    td.r,th.r{text-align:right}
    .tot td{font-weight:bold;background:#f3f4f6}
    @media print{body{padding:0}}
  </style>`
  const moneyHead = `<tr><th>Billed</th><th class="r">Waived</th><th class="r">Net Demand</th><th class="r">Paid</th><th class="r">Balance</th></tr>`

  if (rep.kind === 'student') {
    const s = rep.student as { name: string; roll_number: string; grade: string; section: string; parent_name: string | null; parent_phone: string | null }
    const bal = rep.balance as { billed: number; waived: number; net_demand: number; paid: number; balance: number }
    const bills = rep.bills as Array<{ fee_type: string; period_label: string; billed: number; waived: number; paid: number; balance: number; status: string }>
    const pays = rep.payments as Array<{ receipt_number: string; paid_date: string; fee_type: string; period_label: string; amount: number; payment_mode: string; payment_status: string }>
    const wvs = rep.waivers as Array<{ fee_type: string; period_label: string; waiver_amount: number; reason: string; granted_by_name: string | null; is_revoked: boolean; revoked_by: string | null; revoked_at: string | null; revoke_reason: string | null }>
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Student Fee Report</title>${style}</head><body>${head}
      <h3>Student Profile</h3>
      <table><tr><td><b>Name</b></td><td>${s.name}</td><td><b>Roll No</b></td><td>${s.roll_number}</td><td><b>Class</b></td><td>${s.grade}${s.section || ''}</td></tr>
      <tr><td><b>Parent</b></td><td>${s.parent_name || '—'}</td><td><b>Phone</b></td><td colspan="3">${s.parent_phone || '—'}</td></tr></table>
      <h3>Fee Balance</h3>
      <table><thead>${moneyHead}</thead><tbody><tr class="tot"><td class="r">${RUPEE(bal.billed)}</td><td class="r">${RUPEE(bal.waived)}</td><td class="r">${RUPEE(bal.net_demand)}</td><td class="r">${RUPEE(bal.paid)}</td><td class="r">${RUPEE(bal.balance)}</td></tr></tbody></table>
      <h3>Fee Structure</h3>
      <table><thead><tr><th>Fee Type</th><th>Period</th><th class="r">Billed</th><th class="r">Waived</th><th class="r">Paid</th><th class="r">Balance</th><th>Status</th></tr></thead>
      <tbody>${bills.map(b => `<tr><td>${b.fee_type}</td><td>${b.period_label}</td><td class="r">${RUPEE(b.billed)}</td><td class="r">${RUPEE(b.waived)}</td><td class="r">${RUPEE(b.paid)}</td><td class="r">${RUPEE(b.balance)}</td><td>${b.status}</td></tr>`).join('')}</tbody></table>
      <h3>Payment History</h3>
      <table><thead><tr><th>Receipt</th><th>Date</th><th>Fee · Period</th><th class="r">Amount</th><th>Mode</th><th>Status</th></tr></thead>
      <tbody>${pays.map(p => `<tr><td>${p.receipt_number}</td><td>${p.paid_date}</td><td>${p.fee_type} · ${p.period_label}</td><td class="r">${RUPEE(p.amount)}</td><td>${p.payment_mode}</td><td>${p.payment_status}</td></tr>`).join('') || '<tr><td colspan="6">No payments</td></tr>'}</tbody></table>
      <h3>Waivers</h3>
      <table><thead><tr><th>Fee · Period</th><th class="r">Amount</th><th>Reason</th><th>Granted By</th><th>Status</th><th>Revoke Detail</th></tr></thead>
      <tbody>${wvs.map(w => `<tr><td>${w.fee_type} · ${w.period_label}</td><td class="r">${RUPEE(w.waiver_amount)}</td><td>${w.reason}</td><td>${w.granted_by_name || ''}</td><td>${w.is_revoked ? 'Revoked' : 'Active'}</td><td>${w.is_revoked ? `${w.revoked_by || ''} · ${w.revoked_at ? new Date(w.revoked_at).toLocaleString('en-IN') : ''} · ${w.revoke_reason || ''}` : ''}</td></tr>`).join('') || '<tr><td colspan="6">No waivers</td></tr>'}</tbody></table>
      </body></html>`
  }

  // bulk
  const sm = rep.summary as { billed: number; waived: number; net_demand: number; paid: number; balance: number; students: number }
  const byType = rep.by_type as Array<{ fee_type: string; billed: number; waived: number; net_demand: number; paid: number; balance: number }>
  const byClass = rep.by_class as Array<{ class: string; fee_type: string; billed: number; waived: number; net_demand: number; paid: number; balance: number }>
  const byStudent = rep.by_student as Array<{ student: string; roll_number: string; class: string; fee_type: string; is_subtotal: boolean; billed: number; waived: number; net_demand: number; paid: number; balance: number }>
  const log = rep.change_log as Array<{ at: string; type: string; detail: string; amount: number | null; user: string }>
  const mrow = (o: { billed: number; waived: number; net_demand: number; paid: number; balance: number }) =>
    `<td class="r">${RUPEE(o.billed)}</td><td class="r">${RUPEE(o.waived)}</td><td class="r">${RUPEE(o.net_demand)}</td><td class="r">${RUPEE(o.paid)}</td><td class="r">${RUPEE(o.balance)}</td>`
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Fee Audit Report</title>${style}</head><body>${head}
    <h3>1. Fee Summary <span style="font-weight:normal;color:#888">(${sm.students} students)</span></h3>
    <table><thead>${moneyHead}</thead><tbody><tr class="tot">${mrow(sm)}</tr></tbody></table>
    <h3>2. Fee Type Summary</h3>
    <table><thead><tr><th>Fee Type</th><th class="r">Billed</th><th class="r">Waived</th><th class="r">Net Demand</th><th class="r">Paid</th><th class="r">Balance</th></tr></thead>
    <tbody>${byType.map(t => `<tr><td>${t.fee_type}</td>${mrow(t)}</tr>`).join('')}</tbody></table>
    <h3>3. Fee Change Log</h3>
    <table><thead><tr><th>Date & Time</th><th>Action</th><th>Detail</th><th class="r">Amount</th><th>User</th></tr></thead>
    <tbody>${log.map(l => `<tr><td>${new Date(l.at).toLocaleString('en-IN')}</td><td>${l.type}</td><td>${l.detail}</td><td class="r">${l.amount != null ? RUPEE(l.amount) : ''}</td><td>${l.user || ''}</td></tr>`).join('') || '<tr><td colspan="5">No changes recorded</td></tr>'}</tbody></table>
    <h3>4. Class-wise Fee Details</h3>
    <table><thead><tr><th>Class</th><th>Fee Type</th><th class="r">Billed</th><th class="r">Waived</th><th class="r">Net Demand</th><th class="r">Paid</th><th class="r">Balance</th></tr></thead>
    <tbody>${byClass.map(c => `<tr><td>${c.class}</td><td>${c.fee_type}</td>${mrow(c)}</tr>`).join('')}</tbody></table>
    <h3>5. Student-wise Fee Details <span style="font-weight:normal;color:#888">(by fee type)</span></h3>
    <table><thead><tr><th>Student</th><th>School Roll</th><th>Class</th><th>Fee Type</th><th class="r">Billed</th><th class="r">Waived</th><th class="r">Net Demand</th><th class="r">Paid</th><th class="r">Balance</th></tr></thead>
    <tbody>${byStudent.map(s => s.is_subtotal
      ? `<tr class="tot"><td colspan="3">${s.student}</td><td>SUBTOTAL</td>${mrow(s)}</tr>`
      : `<tr><td>${s.student}</td><td>${s.roll_number}</td><td>${s.class}</td><td>${s.fee_type}</td>${mrow(s)}</tr>`).join('')}</tbody></table>
    </body></html>`
}

type AuditRow = { at: string; who: string; action: string; detail: string; amount: number | null }

// Annual financial report for one academic year: balance sheet, class/category/
// payment-mode breakdowns, month-wise trend, defaulters, the audit log, and the
// Fee Audit Report export (Excel/PDF, school/class/student scope). Subscribes to
// reportsVersion from the shared fee store so actions elsewhere (a payment,
// waiver, cancellation) that invalidate this tab's data trigger a refetch even
// while this tab isn't mounted.
export default function FeeReportsTab({
  schoolId,
  academicYear,
  adminName,
}: {
  schoolId: number
  academicYear: string
  adminName?: string
}) {
  const reportsVersion = useFeeStore(s => s.reportsVersion)

  const [reportData, setReportData]       = useState<ReportData | null>(null)
  const [reportLoading, setReportLoading] = useState(false)
  const [reportError, setReportError]     = useState('')

  const loadReports = useCallback(async () => {
    if (!academicYear) return
    setReportLoading(true)
    try {
      const r = await fetch(`/api/fees/reports?school_id=${schoolId}&academic_year=${academicYear}`)
      if (r.ok) { setReportError(''); setReportData(await r.json()) }
      else setReportError('Could not load reports — try refreshing')
    } catch { setReportError('Network error — reports could not be loaded') }
    finally { setReportLoading(false) }
  }, [schoolId, academicYear])

  useEffect(() => { loadReports() }, [loadReports, reportsVersion])

  const [auditLog, setAuditLog]           = useState<AuditRow[]>([])
  const [auditLoading, setAuditLoading]   = useState(false)
  const [auditLogError, setAuditLogError] = useState('')
  const [showAuditLog, setShowAuditLog]   = useState(false)

  async function loadAuditLog(forceRefresh = false) {
    setShowAuditLog(true)
    if (auditLog.length > 0 && !forceRefresh) return
    setAuditLoading(true); setAuditLogError('')
    try {
      const r = await fetch(`/api/fees/audit-log?school_id=${schoolId}&academic_year=${academicYear}`)
      if (r.ok) setAuditLog(await r.json())
      else setAuditLogError('Could not load audit log — try refreshing')
    } catch { setAuditLogError('Network error — audit log could not be loaded') }
    setAuditLoading(false)
  }

  // ── Fee Audit Report export (Excel / PDF, school / class / student) ──
  const [arScope, setArScope]                   = useState<'school' | 'class'>('school')
  const [arGrade, setArGrade]                   = useState('')
  const [arSection, setArSection]               = useState('all')
  const [arStudentSearch, setArStudentSearch]   = useState('')
  const [arStudentResults, setArStudentResults] = useState<{ id: number; name: string; grade: string; section: string; roll_number: string }[]>([])
  const [arBusy, setArBusy]                     = useState(false)
  const [arMsg, setArMsg]                       = useState('')

  function auditReportQuery(extra: Record<string, string> = {}) {
    const q = new URLSearchParams({ school_id: String(schoolId), academic_year: academicYear })
    if (arScope === 'class' && arGrade && !extra.student_id) {
      q.set('grade', arGrade)
      if (arSection !== 'all') q.set('section', arSection)
    }
    Object.entries(extra).forEach(([k, v]) => q.set(k, v))
    return q.toString()
  }

  function downloadAuditExcel(extra: Record<string, string> = {}) {
    window.open(`/api/fees/audit-report/excel?${auditReportQuery(extra)}`, '_blank')
  }

  async function printAuditPdf(extra: Record<string, string> = {}) {
    setArBusy(true); setArMsg('')
    try {
      const r = await fetch(`/api/fees/audit-report?${auditReportQuery(extra)}`)
      if (!r.ok) { const d = await r.json().catch(() => ({})); setArMsg(d.error || 'Failed to build report'); setArBusy(false); return }
      const rep = await r.json()
      const win = window.open('', '_blank', 'width=1000,height=720')
      if (win) { win.document.write(buildAuditPdfHtml(rep)); win.document.close(); win.print() }
    } catch { setArMsg('Network error') }
    setArBusy(false)
  }

  // Unlike the pre-split version, this always hits /api/students rather than first
  // checking the Passbook tab's already-loaded student directory — that cache lived
  // in the same component and isn't available here now that each tab is separate.
  async function searchAuditStudent(q: string) {
    setArStudentSearch(q)
    if (!q.trim()) { setArStudentResults([]); return }
    const r = await fetch(`/api/students?school_id=${schoolId}`)
    if (r.ok) {
      const data = await r.json()
      const arr = Array.isArray(data) ? data : (data.students || [])
      setArStudentResults(arr.filter((s: { name: string; roll_number: string }) =>
        s.name.toLowerCase().includes(q.toLowerCase()) || (s.roll_number || '').toLowerCase().includes(q.toLowerCase())
      ).slice(0, 10))
    }
  }

  return (
    <div className="space-y-5">
      <LoadErrorBanner message={reportError} onRetry={loadReports} />
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold text-gray-800">Annual Financial Report — {academicYear}</h2>
          <p className="text-xs text-gray-400 mt-0.5">Complete collection analysis for the academic year</p>
        </div>
        <button onClick={loadReports} className="text-sm border border-gray-200 text-gray-600 px-3 py-1.5 rounded-lg hover:bg-gray-50">Refresh</button>
      </div>

      {/* ── Fee Audit Report Export ── */}
      <div className="bg-white rounded-xl border border-gray-100 p-5 space-y-4">
        <div>
          <h3 className="text-sm font-semibold text-gray-700">Fee Audit Report — Export</h3>
          <p className="text-xs text-gray-400 mt-0.5">Summary · By Fee Type · Change Log · Class-wise · Student-wise. Reconciled (Billed → Waived → Net → Paid → Balance).</p>
        </div>

        {/* Scope */}
        <div className="flex items-center gap-3 flex-wrap">
          <span className="text-xs font-medium text-gray-600">Scope:</span>
          <div className="flex rounded-lg border border-gray-200 overflow-hidden text-xs font-medium">
            <button onClick={() => setArScope('school')} className={`px-3 py-1.5 ${arScope === 'school' ? 'bg-blue-600 text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}`}>Whole School</button>
            <button onClick={() => setArScope('class')} className={`px-3 py-1.5 border-l border-gray-200 ${arScope === 'class' ? 'bg-blue-600 text-white' : 'bg-white text-gray-600 hover:bg-gray-50'}`}>One Class</button>
          </div>
          {arScope === 'class' && (
            <>
              <select value={arGrade} onChange={e => setArGrade(e.target.value)} className="text-xs border border-gray-200 rounded-lg px-2 py-1.5 bg-white">
                <option value="">Grade…</option>
                {GRADES.map(g => <option key={g} value={g}>{gradeLabel(g)}</option>)}
              </select>
              <select value={arSection} onChange={e => setArSection(e.target.value)} className="text-xs border border-gray-200 rounded-lg px-2 py-1.5 bg-white">
                <option value="all">All sections</option>
                {['A','B','C','D','E','F'].map(s => <option key={s} value={s}>Sec {s}</option>)}
              </select>
            </>
          )}
        </div>

        {arMsg && <p className="text-xs text-red-600">{arMsg}</p>}

        {/* Format buttons */}
        <div className="flex items-center gap-2">
          <button onClick={() => downloadAuditExcel()} disabled={arScope === 'class' && !arGrade}
            className="text-sm bg-green-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-green-700 disabled:opacity-40">⬇ Excel (.xlsx)</button>
          <button onClick={() => printAuditPdf()} disabled={arBusy || (arScope === 'class' && !arGrade)}
            className="text-sm bg-red-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-red-700 disabled:opacity-40">{arBusy ? 'Building…' : '🖨 PDF (Print)'}</button>
          <span className="text-xs text-gray-400 ml-2">Old CSVs:</span>
          <a href={`/api/fees/export?school_id=${schoolId}&academic_year=${academicYear}&type=ledger`} download className="text-xs text-gray-500 underline">Ledger</a>
          <a href={`/api/fees/export?school_id=${schoolId}&academic_year=${academicYear}&type=payments`} download className="text-xs text-gray-500 underline">Payments</a>
        </div>

        {/* Individual student export */}
        <div className="border-t border-gray-100 pt-4">
          <p className="text-xs font-semibold text-gray-600 mb-2">Individual Student Fee Report</p>
          <div className="relative max-w-md">
            <input type="text" placeholder="Search student by name or roll number…" value={arStudentSearch}
              onChange={e => searchAuditStudent(e.target.value)}
              className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
            {arStudentResults.length > 0 && (
              <div className="absolute z-20 mt-1 left-0 right-0 bg-white border border-gray-200 rounded-lg shadow-lg max-h-64 overflow-y-auto">
                {arStudentResults.map(s => (
                  <div key={s.id} className="px-3 py-2 hover:bg-gray-50 flex items-center justify-between gap-2 border-b border-gray-50 last:border-0">
                    <span className="text-sm text-gray-800">{s.name} <span className="text-xs text-gray-400">Gr.{s.grade}{s.section} · #{s.roll_number}</span></span>
                    <span className="flex gap-1.5 flex-shrink-0">
                      <button onClick={() => { downloadAuditExcel({ student_id: String(s.id) }); setArStudentResults([]); setArStudentSearch('') }}
                        className="text-xs bg-green-600 text-white px-2 py-0.5 rounded hover:bg-green-700">Excel</button>
                      <button onClick={() => { printAuditPdf({ student_id: String(s.id) }); setArStudentResults([]); setArStudentSearch('') }}
                        className="text-xs bg-red-600 text-white px-2 py-0.5 rounded hover:bg-red-700">PDF</button>
                    </span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {reportLoading ? (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[...Array(4)].map((_, i) => <div key={i} className="h-24 bg-white rounded-xl border border-gray-100 animate-pulse" />)}</div>
      ) : reportData ? (
        <>
          {/* Balance sheet */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {[
              { label: 'Total Billed',      val: reportData.balance.total_billed,      color: 'text-gray-800',  bg: 'bg-white' },
              { label: 'Total Collected',   val: reportData.balance.total_collected,   color: 'text-green-700', bg: 'bg-green-50' },
              { label: 'Total Outstanding', val: reportData.balance.total_outstanding, color: 'text-red-600',   bg: 'bg-red-50' },
              { label: 'Total Waived',      val: reportData.balance.discretionary_waived ?? reportData.balance.total_waived, color: 'text-purple-700',bg: 'bg-purple-50' },
            ].map(s => (
              <div key={s.label} className={`${s.bg} rounded-xl border border-gray-100 p-4`}>
                <p className="text-xs text-gray-400 font-medium uppercase tracking-wide">{s.label}</p>
                <p className={`text-2xl font-bold mt-1 ${s.color}`}>{fmt(s.val)}</p>
                <p className="text-xs text-gray-400 mt-1">{reportData.balance.total_students} students</p>
              </div>
            ))}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* Class-wise collection */}
            <div className="bg-white rounded-xl border border-gray-100 p-5">
              <h3 className="text-sm font-semibold text-gray-700 mb-4">Class-wise Collection</h3>
              <div className="space-y-3">
                {reportData.byGrade.map(g => {
                  const netDemand = Number(g.total_due) - Number(g.total_waived ?? 0)
                  const gradePct = pct(Number(g.total_collected), netDemand)
                  const cls = g.section ? `${g.grade}-${g.section}` : `Grade ${g.grade}`
                  const discWaived = Number(g.discretionary_waived ?? 0)
                  return (
                    <div key={cls}>
                      <div className="flex justify-between text-xs mb-1">
                        <span className="font-medium text-gray-700">{cls} <span className="text-gray-400">({g.students} students)</span></span>
                        <span className="text-gray-500">{fmt(g.total_collected)} / {fmt(g.total_due)} <span className="font-bold text-blue-600">{gradePct}%</span></span>
                      </div>
                      <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                        <div className="bg-blue-500 h-full rounded-full" style={{ width: `${gradePct}%` }} />
                      </div>
                      {discWaived > 0 && (
                        <p className="text-[10px] text-purple-500 mt-0.5">Waived: {fmt(discWaived)}</p>
                      )}
                    </div>
                  )
                })}
              </div>
            </div>

            {/* Payment mode breakdown */}
            <div className="bg-white rounded-xl border border-gray-100 p-5">
              <h3 className="text-sm font-semibold text-gray-700 mb-4">Collection by Payment Mode</h3>
              <div className="space-y-3">
                {reportData.byMode.map(m => (
                  <div key={m.payment_mode} className="flex items-center justify-between">
                    <span className="text-sm text-gray-600 capitalize">{m.payment_mode}</span>
                    <div className="text-right">
                      <span className="text-sm font-semibold text-gray-800">{fmt(m.total)}</span>
                      <span className="text-xs text-gray-400 ml-2">({m.count} txns)</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Month-wise billed vs collected */}
          {reportData.monthly.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-100 p-5">
              <h3 className="text-sm font-semibold text-gray-700 mb-4">Month-wise Billed vs Collected</h3>
              <div className="space-y-2">
                {(() => {
                  const dueMap = new Map(reportData.monthlyDue.map(d => [d.month, d.billed]))
                  const allMonths = Array.from(new Set([...reportData.monthly.map(m => m.month), ...reportData.monthlyDue.map(d => d.month)])).sort()
                  const maxVal = Math.max(...allMonths.map(m => Math.max(dueMap.get(m) ?? 0, reportData.monthly.find(x => x.month === m)?.collected ?? 0)), 1)
                  return allMonths.map(month => {
                    const billed    = dueMap.get(month) ?? 0
                    const collected = reportData.monthly.find(x => x.month === month)?.collected ?? 0
                    const billedPct    = Math.round((billed    / maxVal) * 100)
                    const collectedPct = Math.round((collected / maxVal) * 100)
                    const label = new Date(month + '-01').toLocaleDateString('en-IN', { month: 'short', year: '2-digit' })
                    return (
                      <div key={month}>
                        <div className="flex justify-between text-xs mb-1">
                          <span className="font-medium text-gray-600">{label}</span>
                          <span className="text-gray-400">
                            Billed <span className="text-gray-700 font-semibold">{fmt(billed)}</span>
                            {' · '}Collected <span className="text-green-600 font-semibold">{fmt(collected)}</span>
                          </span>
                        </div>
                        <div className="relative h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div className="absolute inset-y-0 left-0 bg-blue-100 rounded-full" style={{ width: `${billedPct}%` }} />
                          <div className="absolute inset-y-0 left-0 bg-green-500 rounded-full" style={{ width: `${collectedPct}%` }} />
                        </div>
                      </div>
                    )
                  })
                })()}
              </div>
              <div className="flex gap-4 mt-3 text-xs text-gray-400">
                <span className="flex items-center gap-1"><span className="w-3 h-2 rounded-full bg-blue-100 inline-block" />Billed</span>
                <span className="flex items-center gap-1"><span className="w-3 h-2 rounded-full bg-green-500 inline-block" />Collected</span>
              </div>
            </div>
          )}

          {/* Category-wise summary */}
          <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
            <div className="px-4 py-3 border-b border-gray-100">
              <p className="text-sm font-semibold text-gray-700">Category-wise Annual Summary</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-100 text-xs text-gray-500">
                    <th className="text-left px-4 py-2.5 font-semibold">Category</th>
                    <th className="text-right px-4 py-2.5 font-semibold">Billed</th>
                    <th className="text-right px-4 py-2.5 font-semibold">Collected</th>
                    <th className="text-right px-4 py-2.5 font-semibold">Waived</th>
                    <th className="text-right px-4 py-2.5 font-semibold">Outstanding</th>
                    <th className="text-center px-4 py-2.5 font-semibold">Paid / Unpaid</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.byCategory.map(c => (
                    <tr key={c.category_name} className="border-b border-gray-50 hover:bg-gray-50">
                      <td className="px-4 py-2.5">
                        <p className="font-medium text-gray-800">{c.category_name}</p>
                        <p className="text-xs text-gray-400 capitalize">{c.frequency} · {c.students} students</p>
                      </td>
                      <td className="px-4 py-2.5 text-right text-gray-700">{fmt(c.total_due)}</td>
                      <td className="px-4 py-2.5 text-right text-green-600 font-medium">{fmt(c.total_collected)}</td>
                      <td className="px-4 py-2.5 text-right text-purple-600">{Number(c.discretionary_waived ?? c.total_waived) > 0 ? fmt(c.discretionary_waived ?? c.total_waived) : '—'}</td>
                      <td className="px-4 py-2.5 text-right text-red-600 font-medium">{fmt(c.outstanding)}</td>
                      <td className="px-4 py-2.5 text-center text-xs">
                        <span className="text-green-600">{c.paid_count} paid</span>
                        <span className="text-gray-300 mx-1">·</span>
                        <span className="text-red-500">{c.unpaid_count} unpaid</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Pending payments list */}
          {reportData.defaulters.length > 0 && (
            <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
              <div className="px-4 py-3 border-b border-gray-100 flex items-center justify-between">
                <p className="text-sm font-semibold text-gray-700">Pending Payments — {reportData.defaulters.length} students</p>
                <a href={`/api/fees/export?school_id=${schoolId}&academic_year=${academicYear}&type=ledger&outstanding=1`} download
                  className="text-xs text-red-600 border border-red-200 px-2.5 py-1 rounded-lg hover:bg-red-50">
                  Export Pending Payments
                </a>
              </div>
              <div className="overflow-x-auto max-h-80">
                <table className="w-full text-sm">
                  <thead className="sticky top-0 bg-gray-50">
                    <tr className="border-b border-gray-100 text-xs text-gray-500">
                      <th className="text-left px-4 py-2 font-semibold">Student</th>
                      <th className="text-left px-4 py-2 font-semibold">Grade</th>
                      <th className="text-left px-4 py-2 font-semibold">Parent / Phone</th>
                      <th className="text-right px-4 py-2 font-semibold">Outstanding</th>
                      <th className="text-center px-4 py-2 font-semibold">Overdue</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.defaulters.map((d, i) => (
                      <tr key={i} className="border-b border-gray-50 hover:bg-gray-50">
                        <td className="px-4 py-2">
                          <p className="font-medium text-gray-800">{d.student_name}</p>
                          <p className="text-xs text-gray-400">#{d.roll_number}</p>
                        </td>
                        <td className="px-4 py-2 text-gray-600">Gr.{d.grade}{d.section}</td>
                        <td className="px-4 py-2 text-xs text-gray-500">{d.parent_name || '—'}{d.parent_phone ? ` · ${d.parent_phone}` : ''}</td>
                        <td className="px-4 py-2 text-right font-bold text-red-600">{fmt(d.outstanding)}</td>
                        <td className="px-4 py-2 text-center">
                          <span className="text-xs bg-red-100 text-red-600 px-1.5 py-0.5 rounded font-medium">{d.overdue_entries}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* ── Audit Log ── */}
          <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
            <div className="px-4 py-3 border-b border-gray-100 flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold text-gray-700">Audit Log — Every Financial Action</p>
                <p className="text-xs text-gray-400">Permanent record of all payments, waivers, edits and config changes. Cannot be deleted.</p>
              </div>
              <div className="flex items-center gap-2">
                <a href={`/api/fees/audit-log?school_id=${schoolId}&academic_year=${academicYear}&format=csv&generated_by=${encodeURIComponent(adminName || 'Admin')}&limit=5000`} download
                  className="text-sm border border-gray-800 text-gray-800 px-3 py-1.5 rounded-lg hover:bg-gray-100">⬇ Export Audit (CSV)</a>
                {!showAuditLog ? (
                  <button onClick={() => loadAuditLog()}
                    className="text-sm bg-gray-800 text-white px-4 py-1.5 rounded-lg hover:bg-gray-900">View Audit Log</button>
                ) : (
                  <>
                    <button onClick={() => loadAuditLog(true)}
                      className="text-sm border border-gray-200 text-gray-600 px-3 py-1.5 rounded-lg hover:bg-gray-50">Refresh</button>
                    <button onClick={() => setShowAuditLog(false)}
                      className="text-sm border border-gray-200 text-gray-600 px-3 py-1.5 rounded-lg hover:bg-gray-50">Hide</button>
                  </>
                )}
              </div>
            </div>
            {showAuditLog && (
              auditLoading ? (
                <p className="text-sm text-gray-400 p-8 text-center">Loading audit log…</p>
              ) : auditLogError ? (
                <p className="text-sm text-red-500 p-8 text-center">{auditLogError}</p>
              ) : auditLog.length === 0 ? (
                <p className="text-sm text-gray-400 p-8 text-center">No financial actions recorded yet.</p>
              ) : (
                <div className="overflow-x-auto max-h-[480px]">
                  <table className="w-full text-sm">
                    <thead className="sticky top-0 bg-gray-50">
                      <tr className="text-xs text-gray-500 border-b border-gray-100">
                        <th className="text-left px-4 py-2 font-semibold whitespace-nowrap">Date / Time</th>
                        <th className="text-left px-4 py-2 font-semibold">Who</th>
                        <th className="text-left px-4 py-2 font-semibold">Action</th>
                        <th className="text-left px-4 py-2 font-semibold">Detail</th>
                        <th className="text-right px-4 py-2 font-semibold">Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                      {auditLog.map((a, i) => {
                        const actionColor =
                          a.action.includes('rejected') || a.action.includes('revoked') ? 'text-red-600' :
                          a.action.includes('Payment recorded') ? 'text-green-600' :
                          a.action.includes('Waiver granted') ? 'text-purple-600' :
                          a.action.includes('edited') || a.action.includes('changed') ? 'text-amber-600' :
                          'text-gray-600'
                        return (
                          <tr key={i} className="border-b border-gray-50 hover:bg-gray-50">
                            <td className="px-4 py-2 text-gray-500 text-xs whitespace-nowrap">
                              {new Date(a.at).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: '2-digit', hour: '2-digit', minute: '2-digit' })}
                            </td>
                            <td className="px-4 py-2 text-gray-700">{a.who}</td>
                            <td className={`px-4 py-2 font-medium ${actionColor}`}>{a.action}</td>
                            <td className="px-4 py-2 text-gray-500 text-xs">{a.detail}</td>
                            <td className="px-4 py-2 text-right text-gray-700">{a.amount != null ? fmt(a.amount) : '—'}</td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              )
            )}
          </div>
        </>
      ) : (
        <div className="bg-white rounded-xl border border-dashed border-gray-200 p-12 text-center">
          <p className="text-gray-400 text-sm">Click Refresh to load the annual report.</p>
        </div>
      )}
    </div>
  )
}
